const day2Words = [
  { word: "virtually", synonyms: ["In effect", "almost", "essentially", "nearly"], meaning: "사실상, 거의" },
  { word: "unprecedented", synonyms: ["Unlike anything in the past", "unique", "novel", "new"], meaning: "전례없는" },
  { word: "Grow accustomed to", synonyms: ["Become used to", "become familiar with"], meaning: "~에 익숙해지다" },
  { word: "intrigue", synonyms: ["Interest", "fascinate", "attract"], meaning: "흥미를 끌다" },
  { word: "implausible", synonyms: ["Unlikely", "unbelievable", "improbable"], meaning: "믿기 어려운" },
  { word: "decline", synonyms: ["Weakening", "decay", "Decrease", "lessen", "fall", "Refuse", "reject"], meaning: "쇠퇴 / 감소하다 / 거절하다" },
  { word: "contemporary", synonyms: ["Modern", "present-day", "current", "Coexisting", "concurrent"], meaning: "현대의 / 동시대의" },
  { word: "allocate", synonyms: ["Distribute", "allot", "designate", "earmark"], meaning: "할당하다" },
  { word: "drastically", synonyms: ["Severely", "strikingly", "extremely"], meaning: "극심하게" },
  { word: "heterogeneous", synonyms: ["Varied", "assorted", "mixed"], meaning: "혼성의" },
  { word: "conspicuous", synonyms: ["Noticeable", "clearly", "visible", "prominent", "obvious"], meaning: "뚜렷한" },
  { word: "prolific", synonyms: ["Fertile", "fruitful", "productive", "abundant"], meaning: "풍부한" },
  { word: "fluctuation", synonyms: ["Change", "variation", "variance"], meaning: "변동" },
  { word: "encourage", synonyms: ["Promote", "motivate", "prompt"], meaning: "촉진하다" },
  { word: "abrupt", synonyms: ["Sudden", "unexpected"], meaning: "갑작스러운" },
  { word: "evaluate", synonyms: ["Judge", "assess", "appraise", "gauge"], meaning: "평가하다" },
  { word: "comprehensive", synonyms: ["Thorough", "exhaustive", "complete"], meaning: "종합적인" },
  { word: "Engrave", synonyms: ["Carve", "incise", "etch"], meaning: "새기다" },
  { word: "Slight", synonyms: ["Minor", "small", "trivial", "mild"], meaning: "경미한" },
  { word: "monotonous", synonyms: ["Unvaried", "boring", "tedious", "dull"], meaning: "단조로운" },
  { word: "Regard", synonyms: ["Consider", "think of", "see"], meaning: "생각하다" },
  { word: "Obsession with", synonyms: ["Attention", "notice", "Fixation on", "preoccupation with"], meaning: "관심 / 집착" },
  { word: "optimize", synonyms: ["Make the best use of"], meaning: "최대한 잘 활용하다" },
  { word: "supplant", synonyms: ["Replace", "substitute", "displace", "supersede"], meaning: "대체하다" },
  { word: "Colossal", synonyms: ["Enormous", "monstrous", "gigantic"], meaning: "거대한" },
  { word: "Diffuse", synonyms: ["Spread", "distribute", "scatter"], meaning: "퍼뜨리다" },
  { word: "mechanics", synonyms: ["Procedure"], meaning: "방법" },
  { word: "Susceptible to", synonyms: ["Likely to", "vulnerable to", "prone to"], meaning: "~에 걸리기 쉬운" },
  { word: "emanate", synonyms: ["Emerge", "spring", "originate"], meaning: "빛 등이 나다" },
  { word: "conventionally", synonyms: ["Customarily", "traditionally"], meaning: "관례적으로" },
  { word: "expansive", synonyms: ["Large", "broad", "wide", "extensive"], meaning: "넓은" },
  { word: "sporadically", synonyms: ["Occasionally", "at intervals", "infrequently"], meaning: "이따끔씩" },
  { word: "comparative", synonyms: ["Relative"], meaning: "상대적인" },
  { word: "Stamp out", synonyms: ["Eliminate", "eradicate", "extirpate"], meaning: "근절하다" },
  { word: "stagnation", synonyms: ["Low growth", "downturn"], meaning: "침체" },
  { word: "innate", synonyms: ["Inborn", "natural", "native"], meaning: "선천적인" },
  { word: "Obsolete", synonyms: ["Out of date", "outdated", "unused", "out of use"], meaning: "쓸모없게 된" },
  { word: "specify", synonyms: ["State", "define", "stipulate"], meaning: "명시하다" },
  { word: "endure", synonyms: ["Tolerate", "survive", "suffer", "persevere", "Last", "continue", "persist"], meaning: "견디다 / 지속하다" },
  { word: "conceivable", synonyms: ["Imaginable", "thinkable", "possible"], meaning: "생각할 수 있는" },
  { word: "sufficiently", synonyms: ["Adequately", "amply", "satisfactorily"], meaning: "충분히" },
  { word: "entail", synonyms: ["Involve", "cause", "Require", "demand"], meaning: "수반하다 / 필요로하다" },
  { word: "depict", synonyms: ["Picture", "portray", "represent"], meaning: "묘사하다" },
  { word: "integration", synonyms: ["Union", "unification"], meaning: "통합" },
  { word: "stockpile", synonyms: ["Store up", "save", "reserve"], meaning: "비축하다" },
  { word: "capture", synonyms: ["Seize", "catch", "trap", "grab"], meaning: "붙잡다" },
  { word: "landscape", synonyms: ["Scenery", "scene", "view"], meaning: "풍경" },
  { word: "elaborately", synonyms: ["With great detail"], meaning: "정교하게" },
  { word: "autonomous", synonyms: ["Independent", "self-determining"], meaning: "자율적인" },
  { word: "boom", synonyms: ["Flourish", "thrive", "prosper", "rapidly expand"], meaning: "갑자기 번창하다" },
  { word: "supremacy", synonyms: ["Dominance", "predominance", "ascendancy"], meaning: "우위" },
  { word: "ravage", synonyms: ["Destroy", "demolish", "devastate", "ruin"], meaning: "파괴하다" },
  { word: "authority", synonyms: ["Expert", "master", "specialist"], meaning: "권위자" },
  { word: "plug", synonyms: ["Fill up", "stuff", "pack"], meaning: "매우다" },
  { word: "discrepancy", synonyms: ["Inconsistency", "disparity", "dissimilarity"], meaning: "불일치" },
  { word: "elucidate", synonyms: ["Clarify", "explain", "make clear"], meaning: "설명하다" },
];

const day3Words = [
  { word: "simultaneous", synonyms: ["Concurrent", "happening at the same time", "synchronous"], meaning: "동시의" },
  { word: "vast", synonyms: ["Extensive", "immense", "great", "huge", "enormous"], meaning: "광대한" },
  { word: "reluctant", synonyms: ["Unwilling", "disinclined", "loath"], meaning: "꺼리는" },
  { word: "conjecture", synonyms: ["Speculation", "guess", "supposition"], meaning: "추측" },
  { word: "embed", synonyms: ["Fix", "insert", "implant", "root"], meaning: "박아넣다" },
  { word: "vow", synonyms: ["Pledge", "promise", "oath"], meaning: "서약" },
  { word: "counter", synonyms: ["Oppose", "act against", "refute"], meaning: "반박하다" },
  { word: "apparent", synonyms: ["Clear", "evident", "obvious", "Seeming", "exterior", "superficial"], meaning: "분명한 / 외관상의" },
  { word: "bombard", synonyms: ["Strike", "assail", "attack"], meaning: "폭격하다" },
  { word: "reveal", synonyms: ["Make known", "show", "unveil", "uncover", "expose"], meaning: "밝히다" },
  { word: "sturdy", synonyms: ["Well-built", "strong", "robust", "stalwart"], meaning: "튼튼한" },
  { word: "traditionally", synonyms: ["Typically"], meaning: "관습적으로" },
  { word: "correspondingly", synonyms: ["Similarly", "likewise"], meaning: "그에 상응하여" },
  { word: "Trigger", synonyms: ["Cause", "generate", "initiate", "start", "stimulate", "activate"], meaning: "일으키다" },
  { word: "vigorous", synonyms: ["Strong and healthy", "strong", "energetic"], meaning: "강건한" },
  { word: "spontaneous", synonyms: ["Forceful", "Voluntary", "unprompted", "Automatic", "unplanned", "involuntary"], meaning: "강력한 / 자발적인 / 무의식적인" },
  { word: "miniature", synonyms: ["Small", "tiny", "diminutive"], meaning: "소형의" },
  { word: "commission", synonyms: ["Order", "hire"], meaning: "의뢰하다" },
  { word: "remarkable", synonyms: ["Extraordinary", "incredible", "notable", "significant"], meaning: "놀라운" },
  { word: "effort", synonyms: ["Attempt", "endeavor", "exertion"], meaning: "노력" },
  { word: "manifestation", synonyms: ["Indication", "symptom", "evidence", "sign"], meaning: "짓후" },
  { word: "prior", synonyms: ["Previous", "former", "earlier"], meaning: "이전의" },
  { word: "Cast about", synonyms: ["Seek", "search", "hunt"], meaning: "찾아다니다" },
  { word: "rigorous", synonyms: ["Strict", "severe", "demanding", "precise"], meaning: "엄격한" },
  { word: "Harsh", synonyms: ["Strict", "severe"], meaning: "혹독한" },
  { word: "compulsory", synonyms: ["Obligatory", "forced", "required", "necessary"], meaning: "의무적인" },
  { word: "subsidiary", synonyms: ["Less important", "auxiliary", "subordinate"], meaning: "부수적인" },
  { word: "status", synonyms: ["Standing", "prestige", "importance"], meaning: "지위" },
  { word: "emphasize", synonyms: ["Stress", "highlight", "underline"], meaning: "강조하다" },
  { word: "largely", synonyms: ["Generally", "mostly", "mainly"], meaning: "대부분" },
  { word: "experimental", synonyms: ["Trial", "tentative"], meaning: "시험적인" },
  { word: "drain", synonyms: ["Withdraw liquid", "gradually remove water"], meaning: "물을 빼내다" },
  { word: "denote", synonyms: ["Indicate", "signify", "represent"], meaning: "나타내다" },
  { word: "repudiate", synonyms: ["Reject", "disclaim"], meaning: "거부하다" },
  { word: "contradictory", synonyms: ["Inconsistent", "paradoxical", "conflicting"], meaning: "모순되는" },
  { word: "propagate", synonyms: ["Multiply", "reproduce"], meaning: "번식하다" },
  { word: "ensure", synonyms: ["Guarantee", "assure", "warrant"], meaning: "보장하다" },
  { word: "pore", synonyms: ["Hole", "Stare", "gaze"], meaning: "구멍 / 응시하다" },
  { word: "alternate", synonyms: ["Take turns", "rotate", "interchange"], meaning: "번갈아 일어나다" },
  { word: "devastating", synonyms: ["Destructive", "ruinous"], meaning: "파괴적인" },
  { word: "Mingle with", synonyms: ["Associate with", "mix with", "consort with"], meaning: "~와 어울리다" },
  { word: "continued", synonyms: ["Ongoing", "constant", "incessant", "ceaseless"], meaning: "계속적인" },
  { word: "attempt", synonyms: ["Try", "seek", "endeavor"], meaning: "시도하다" },
  { word: "subterfuge", synonyms: ["Trick", "deception"], meaning: "속임수" },
  { word: "convert", synonyms: ["Change", "transform"], meaning: "바꾸다" },
  { word: "contention", synonyms: ["Debate", "argument", "disagreement"], meaning: "논쟁" },
  { word: "migrate", synonyms: ["Move around", "travel"], meaning: "이주하다" },
  { word: "succession", synonyms: ["Sequence", "series"], meaning: "연속" },
  { word: "tentativeness", synonyms: ["Hesitation", "indecision"], meaning: "망설임" },
  { word: "fragmentary", synonyms: ["Incomplete", "fractional", "partial"], meaning: "단편적인" },
  { word: "legendary", synonyms: ["Famous", "Mythical"], meaning: "유명한 / 전설상의" },
  { word: "setback", synonyms: ["Defeat", "reverse"], meaning: "패배" },
  { word: "Fine-tune", synonyms: ["Adjust slightly"], meaning: "미세하게 조정하다" },
  { word: "enthusiastic", synonyms: ["Eager", "ardent", "zealous"], meaning: "열광적인" },
  { word: "loose", synonyms: ["Not strict", "relaxed", "slack"], meaning: "느슨한" },
  { word: "portrait", synonyms: ["Picture"], meaning: "초상화" },
  { word: "terminology", synonyms: ["Vocabulary", "jargon", "language"], meaning: "전문용어" },
];

const day4Words = [
  { word: "readily", synonyms: ["Easily", "effortlessly", "quickly", "Willingly", "without reluctance"], meaning: "즉시 / 기꺼이" },
  { word: "advocate", synonyms: ["Promote", "speak in favor of", "argue in support of", "Proponent", "supporter", "upholder"], meaning: "지지하다 / 지지자" },
  { word: "utterly", synonyms: ["Completely", "totally"], meaning: "완전히" },
  { word: "abound", synonyms: ["Overflow", "teem", "be plentiful", "be numerous"], meaning: "풍부하다" },
  { word: "formidable", synonyms: ["Impressive", "Difficult to handle"], meaning: "어마어마한 / 감당하기 어려운" },
  { word: "enormous", synonyms: ["Huge", "very large", "great", "immense", "vast", "tremendous"], meaning: "거대한" },
  { word: "disband", synonyms: ["Dismiss", "disperse", "break up"], meaning: "해산시키다" },
  { word: "alleged", synonyms: ["Supposed", "assumed"], meaning: "추정의" },
  { word: "renowned", synonyms: ["Famous", "celebrated", "prominent", "eminent"], meaning: "유명한" },
  { word: "versatile", synonyms: ["Adaptable", "flexible"], meaning: "다방면의" },
  { word: "prohibitive", synonyms: ["Unaffordable", "extreme", "exorbitant"], meaning: "값이 비싼" },
  { word: "option", synonyms: ["Choice", "selection"], meaning: "선택" },
  { word: "inherent", synonyms: ["Innate", "built-in", "essential", "congenital"], meaning: "타고난" },
  { word: "justly", synonyms: ["Rightfully", "justifiably", "lawfully"], meaning: "공정하게" },
  { word: "provoke", synonyms: ["Incite", "bring about", "give rise to"], meaning: "불러일으키다" },
  { word: "impermeable", synonyms: ["Impenetrable", "impervious"], meaning: "침투되지 않는" },
  { word: "momentous", synonyms: ["Significant", "major", "meaningful", "substantial"], meaning: "중대한" },
  { word: "forestall", synonyms: ["Prevent", "hinder", "avert"], meaning: "미연에 방지하다" },
  { word: "therefore", synonyms: ["Consequently", "as a result", "thus", "hence"], meaning: "그 결과" },
  { word: "persuade", synonyms: ["Convince", "induce"], meaning: "설득하다" },
  { word: "proximity", synonyms: ["Closeness", "nearness"], meaning: "가까움" },
  { word: "dependable", synonyms: ["Reliable", "trustworthy"], meaning: "신뢰할 수 있는" },
  { word: "ensuing", synonyms: ["Subsequent", "following", "succeeding"], meaning: "뒤이은" },
  { word: "appreciably", synonyms: ["Noticeably", "significantly", "considerably"], meaning: "상당히" },
  { word: "obligate", synonyms: ["Force", "coerce", "compel", "constrain"], meaning: "강요하다" },
  { word: "wholesale", synonyms: ["Extensive", "mass", "Completely"], meaning: "대규모의 / 모조리" },
  { word: "dweller", synonyms: ["Inhabitant", "resident", "occupant"], meaning: "거주자" },
  { word: "tacit", synonyms: ["Implicit", "implied", "unspoken"], meaning: "암묵적인" },
  { word: "resolve", synonyms: ["Settle", "find a solution for", "solve"], meaning: "해결하다" },
  { word: "merit", synonyms: ["Value", "worth", "virtue"], meaning: "가치" },
  { word: "notion", synonyms: ["Concept", "general idea", "opinion", "view"], meaning: "개념" },
  { word: "synthesize", synonyms: ["Integrate", "combine", "coalesce"], meaning: "통합하다" },
  { word: "spectrum", synonyms: ["Range", "scope", "extent"], meaning: "범위" },
  { word: "stream", synonyms: ["Flow", "current"], meaning: "흐름" },
  { word: "rupture", synonyms: ["Burst", "break apart", "split", "tear", "Breach", "discord"], meaning: "파열되다 / 불화" },
  { word: "presuppose", synonyms: ["Assume", "suppose", "presume"], meaning: "가정하다" },
  { word: "Well-to-do", synonyms: ["Wealthy", "affluent", "rich"], meaning: "부유한" },
  { word: "appeal", synonyms: ["Plead", "request", "ask", "beg"], meaning: "간청하다" },
  { word: "accurately", synonyms: ["Correctly", "precisely", "exactly"], meaning: "정확하게" },
  { word: "fastidious", synonyms: ["Demanding", "choosy"], meaning: "까다로운" },
  { word: "contraction", synonyms: ["Reduction", "diminution"], meaning: "감소" },
  { word: "stimulus", synonyms: ["Impetus", "motivation", "incentive", "incitement"], meaning: "자극" },
  { word: "track", synonyms: ["Follow", "chase", "monitor"], meaning: "뒤쫓다" },
  { word: "tame", synonyms: ["Domesticate", "train"], meaning: "길들이다" },
  { word: "install", synonyms: ["Put in place", "set up", "position"], meaning: "설치하다" },
  { word: "chronicle", synonyms: ["Record", "history"], meaning: "기록" },
  { word: "novel", synonyms: ["New", "innovative", "unusual"], meaning: "새로운" },
  { word: "Isolated", synonyms: ["Remote", "solitary", "secluded"], meaning: "외딴" },
  { word: "exposed", synonyms: ["Visible", "uncovered", "revealed"], meaning: "드러난" },
  { word: "intermingled", synonyms: ["Mixed", "combined", "blended"], meaning: "섞인" },
  { word: "succulent", synonyms: ["Juicy", "pulpy"], meaning: "즙이 많은" },
  { word: "homogeneous", synonyms: ["Unvarying", "akin"], meaning: "동종의" },
  { word: "era", synonyms: ["Period", "epoch", "age"], meaning: "시대" },
  { word: "threat", synonyms: ["Intention to harm", "menace"], meaning: "위협" },
  { word: "foul", synonyms: ["Pollute", "contaminate"], meaning: "더럽히다" },
  { word: "prey", synonyms: ["Victim"], meaning: "희생자" },
  { word: "practically", synonyms: ["Nearly"], meaning: "거의" },
];

const day5Words = [
  { word: "compelling", synonyms: ["Convincing", "persuasive", "cogent"], meaning: "설득력있는" },
  { word: "ultimately", synonyms: ["Eventually", "finally", "in the end", "lastly"], meaning: "마침내" },
  { word: "bulk", synonyms: ["Mass", "large quantity", "great quantity", "Majority", "main part"], meaning: "대량 / 대부분" },
  { word: "incompatible", synonyms: ["In conflict", "discrepant", "contradictory"], meaning: "양립할 수 없는" },
  { word: "substantially", synonyms: ["Significantly", "considerably", "Largely", "mainly"], meaning: "상당히 / 대체로" },
  { word: "seek", synonyms: ["Look for", "search for", "pursue"], meaning: "찾다" },
  { word: "unanticipated", synonyms: ["Not expected", "unforeseen", "Attempt", "try", "essay"], meaning: "예상하지 못한" },
  { word: "merge", synonyms: ["Combine", "blend", "fuse"], meaning: "합치다" },
  { word: "encounter", synonyms: ["Meet", "experience", "confront", "face"], meaning: "마주치다" },
  { word: "Residue", synonyms: ["Remains", "remainder", "remnant"], meaning: "잔여물" },
  { word: "circumstance", synonyms: ["Condition", "situation"], meaning: "상황" },
  { word: "astonishing", synonyms: ["Incredible", "amazing", "startling", "astounding"], meaning: "놀라운" },
  { word: "intermittently", synonyms: ["Occasionally", "periodically", "from time to time"], meaning: "간헐적으로" },
  { word: "application", synonyms: ["Use", "utilization", "employment"], meaning: "응용" },
  { word: "predominant", synonyms: ["Principal", "main", "primary", "leading"], meaning: "주된" },
  { word: "remote", synonyms: ["Distant", "secluded", "removed"], meaning: "멀리 떨어진" },
  { word: "inordinate", synonyms: ["Excessive", "exorbitant", "undue"], meaning: "과도한" },
  { word: "launch", synonyms: ["Start", "begin", "initiate", "commence"], meaning: "시작하다" },
  { word: "trend", synonyms: ["Tendency", "inclination", "direction"], meaning: "경향" },
  { word: "embodiment", synonyms: ["Concrete example", "epitome"], meaning: "전형, 구체화된 것" },
  { word: "colonize", synonyms: ["Inhabit", "populate", "Conquer"], meaning: "서식하다 / 식민지화하다" },
  { word: "affect", synonyms: ["Influence", "impact", "act on"], meaning: "영향을 미치다" },
  { word: "speculation", synonyms: ["Supposition", "conjecture", "surmise"], meaning: "추측" },
  { word: "compound", synonyms: ["Add to", "intensify", "worsen"], meaning: "더하다, 악화시키다" },
  { word: "fascinating", synonyms: ["Extremely attractive", "captivating", "enthralling"], meaning: "매혹적인" },
  { word: "constellation", synonyms: ["Collection", "combination", "group"], meaning: "모임, 무리" },
  { word: "unconsolidated", synonyms: ["Loose", "incoherent"], meaning: "굳지 않은" },
  { word: "outstanding", synonyms: ["Excellent", "remarkable", "prominent", "Unpaid", "unsettled", "owing"], meaning: "뛰어난 / 미지불의, 처리되지 않은" },
  { word: "outcome", synonyms: ["Result", "consequence", "conclusion"], meaning: "결과" },
  { word: "document", synonyms: ["Record", "report", "paper"], meaning: "문서 기록" },
  { word: "intrinsically", synonyms: ["Fundamentally", "essentially"], meaning: "본질적으로" },
  { word: "disputatious", synonyms: ["Contentious", "argumentative", "quarrelsome"], meaning: "논쟁을 좋아하는" },
  { word: "diverse", synonyms: ["Varied", "various", "manifold", "dissimilar"], meaning: "다양한" },
  { word: "eerie", synonyms: ["Odd", "strange"], meaning: "기묘한" },
  { word: "tenuous", synonyms: ["Weak", "insubstantial"], meaning: "빈약한" },
  { word: "eradicate", synonyms: ["Remove", "root up", "extirpate", "eliminate"], meaning: "근절하다" },
  { word: "Prone to", synonyms: ["Susceptible to", "likely to"], meaning: "~하기 쉬운" },
  { word: "lodge", synonyms: ["Embed", "implant"], meaning: "박히다" },
  { word: "Gather momentum", synonyms: ["Make progress", "gain impetus"], meaning: "탄력이 붙다" },
  { word: "viable", synonyms: ["Able to survive"], meaning: "생존 가능한" },
  { word: "impediment", synonyms: ["Obstacle", "obstruction", "barrier"], meaning: "장애물" },
  { word: "arid", synonyms: ["Dry", "barren", "sterile", "waterless"], meaning: "메마른" },
  { word: "credible", synonyms: ["Believable", "reliable", "plausible"], meaning: "믿을 수 있는" },
  { word: "vacate", synonyms: ["Abandon", "evacuate", "void"], meaning: "떠나다" },
  { word: "cushion", synonyms: ["Protect", "buffer"], meaning: "보화다" },
  { word: "peculiar", synonyms: ["Unique", "distinct", "particular", "Strange", "unusual", "odd"], meaning: "특유의 / 이상한" },
  { word: "Attributable to", synonyms: ["Caused by", "ascribable to"], meaning: "~에 기인하는" },
  { word: "Enact", synonyms: ["Make into law", "establish", "pass", "adopt"], meaning: "제정하다" },
  { word: "stratified", synonyms: ["Layered"], meaning: "층으로 이루어진" },
  { word: "With regard to", synonyms: ["In terms of", "with respect to", "concerning"], meaning: "~에 관하여" },
  { word: "turbulent", synonyms: ["Violent", "agitated", "tumultuous"], meaning: "격동하는" },
  { word: "appraisal", synonyms: ["Evaluation", "assessment", "estimation"], meaning: "평가" },
  { word: "erroneous", synonyms: ["Wrong", "incorrect", "mistaken", "false"], meaning: "잘못된" },
  { word: "proponent", synonyms: ["Supporter", "adherent", "partisan", "advocate"], meaning: "지지자" },
  { word: "absolute", synonyms: ["Unqualified", "complete", "utter"], meaning: "절대적인" },
  { word: "gratify", synonyms: ["Satisfy", "please"], meaning: "만족시키다" },
];

const day6Words = [
  { word: "disperse", synonyms: ["Scatter", "dissipate", "spread", "disseminate"], meaning: "흩어지게 하다, 퍼뜨리다" },
  { word: "adjacent", synonyms: ["nearby", "neighboring", "adjoining"], meaning: "인접한" },
  { word: "sequence", synonyms: ["Progression", "series", "string", "succession", "order"], meaning: "연속; 순서" },
  { word: "detect", synonyms: ["discover", "find", "recognize", "sense"], meaning: "발견하다, 인지하다" },
  { word: "flexible", synonyms: ["Pliable", "bendable", "adaptable", "adjustable"], meaning: "유연한; 적응성 있는" },
  { word: "surpass", synonyms: ["Exceed", "outrun", "be higher than", "excel"], meaning: "능가하다" },
  { word: "invariable", synonyms: ["Constant", "consistent", "unchanging"], meaning: "변함없는" },
  { word: "dramatic", synonyms: ["Striking", "significant", "impressive"], meaning: "극적인, 인상적인" },
  { word: "master", synonyms: ["Learn thoroughly", "acquire", "control", "manage"], meaning: "습득하다; 제어하다" },
  { word: "assimilate", synonyms: ["Absorb", "take in", "digest"], meaning: "(지식 등을) 흡수하다, 이해하다" },
  { word: "overwhelming", synonyms: ["Powerful", "enormous", "compelling", "tremendous"], meaning: "압도적인, 굉장한" },
  { word: "curious", synonyms: ["inquisitive", "questioning", "inquiring", "strange", "mysterious", "extraordinary"], meaning: "호기심이 강한; 이상한, 별난" },
  { word: "alternation", synonyms: ["Change", "modification"], meaning: "변화, 수정" },
  { word: "consequence", synonyms: ["Result", "effect", "ramification", "outcome", "importance", "significance"], meaning: "결과; 중요성" },
  { word: "deceive", synonyms: ["Mislead", "delude", "cheat"], meaning: "속이다" },
  { word: "ample", synonyms: ["Sizable", "large", "spacious", "vast", "plentiful", "abundant", "more than enough"], meaning: "넓은, 광대한; 풍부한" },
  { word: "resilient", synonyms: ["Quick to recover", "easy to recover"], meaning: "금방 회복하는" },
  { word: "Detach", synonyms: ["Separate", "disconnect", "disengage"], meaning: "분리하다" },
  { word: "account", synonyms: ["Description", "report", "narrative"], meaning: "(사건 등에 대한) 기술, 보고" },
  { word: "equilibrium", synonyms: ["Balance", "symmetry"], meaning: "균형" },
  { word: "surmise", synonyms: ["Infer", "guess", "speculate", "suspect"], meaning: "추측하다" },
  { word: "unsuitable", synonyms: ["Inappropriate", "unfit", "improper"], meaning: "적합하지 않은" },
  { word: "imaginative", synonyms: ["Creative", "inventive", "original"], meaning: "창의적인" },
  { word: "imposing", synonyms: ["Impressive", "striking"], meaning: "인상적인" },
  { word: "Vitality", synonyms: ["Energy", "liveliness", "vigor"], meaning: "활력" },
  { word: "Vehicle", synonyms: ["Means", "medium", "instrument"], meaning: "수단, 매체" },
  { word: "hitherto", synonyms: ["Previously", "so far", "until now"], meaning: "지금까지" },
  { word: "Plague", synonyms: ["Cause a problem for", "bother", "annoy"], meaning: "괴롭히다" },
  { word: "domain", synonyms: ["Area", "field"], meaning: "영역" },
  { word: "indifferent", synonyms: ["Uninterested", "unconcerned", "careless"], meaning: "무관심한" },
  { word: "champion", synonyms: ["Support", "promote", "advocate", "endorse"], meaning: "옹호하다" },
  { word: "deteriorate", synonyms: ["Get worse", "degenerate"], meaning: "악화되다" },
  { word: "Assault", synonyms: ["Attack", "aggress", "assail"], meaning: "폭행하다, 공격하다" },
  { word: "appropriate", synonyms: ["Suitable", "proper", "applicable"], meaning: "적절한" },
  { word: "Adept", synonyms: ["Skillful", "proficient", "deft", "adroit"], meaning: "능숙한" },
  { word: "Indeed", synonyms: ["In truth", "in fact"], meaning: "사실은" },
  { word: "Pursuit", synonyms: ["Interest", "pastime", "hobby"], meaning: "취미, 오락" },
  { word: "Incite", synonyms: ["Stimulate", "provoke", "inflame", "spur"], meaning: "자극하다" },
  { word: "guarantee", synonyms: ["Ensure", "secure", "warrant"], meaning: "보장하다" },
  { word: "prosperity", synonyms: ["Economic well-being", "wealth", "fortune"], meaning: "번영" },
  { word: "primarily", synonyms: ["Mostly", "mainly", "chiefly", "originally", "at first", "initially"], meaning: "주로; 원래, 처음에" },
  { word: "Erupt", synonyms: ["Explode", "burst", "blow up"], meaning: "폭발하다" },
  { word: "Trace", synonyms: ["Evidence", "vestige", "imprint", "mark"], meaning: "자취, 흔적" },
  { word: "prestigious", synonyms: ["Highly regarded", "esteemed", "respected"], meaning: "명성이 있는" },
  { word: "Shape", synonyms: ["Affect", "form", "influence"], meaning: "(영향을 미쳐) 형성하다" },
  { word: "Inflict", synonyms: ["Cause", "administer", "exact"], meaning: "(고통 등을) 주다, 가하다" },
  { word: "portion", synonyms: ["Part", "segment", "fragment"], meaning: "부분" },
  { word: "coincidence", synonyms: ["Chance happening"], meaning: "우연의 일치" },
  { word: "Propel", synonyms: ["Push", "force", "drive", "impel"], meaning: "몰아내다" },
  { word: "thoroughly", synonyms: ["Completely", "entirely"], meaning: "철저히, 완전히" },
  { word: "contemplate", synonyms: ["Consider", "ponder"], meaning: "곰곰이 생각하다" },
  { word: "unethical", synonyms: ["Improper", "immoral"], meaning: "비윤리적인" },
  { word: "replicate", synonyms: ["Reproduce", "copy", "duplicate"], meaning: "모사하다, 복제하다" },
  { word: "Hasty", synonyms: ["Hurried", "rushed"], meaning: "황급한, 서두르는" },
  { word: "representative", synonyms: ["Indicative", "typical", "exemplary"], meaning: "나타나는, 전형적인" },
  { word: "Range", synonyms: ["Scope", "spectrum", "extent"], meaning: "범위" },
];

const day7Words = [
  { word: "considerable", synonyms: ["Substantial", "a large amount of", "large", "meaningful", "significant"], meaning: "상당한; 중요한" },
  { word: "dominate", synonyms: ["Control", "govern", "rule", "be widespread in"], meaning: "지배하다; 압도적으로 우세하다" },
  { word: "Ratio", synonyms: ["proportion", "rate", "percentage"], meaning: "비율" },
  { word: "duplicate", synonyms: ["Copy", "reproduce", "imitate", "repeat"], meaning: "복제하다; 되풀이하다" },
  { word: "barely", synonyms: ["Hardly", "scarcely", "almost not", "just", "only just"], meaning: "거의~않게, 간신히" },
  { word: "Strew", synonyms: ["Scatter", "sprinkle", "disperse"], meaning: "흩뿌리다" },
  { word: "legitimately", synonyms: ["properly", "lawfully", "legally"], meaning: "합법적으로, 정당하게" },
  { word: "encapsulate", synonyms: ["Summarize", "sum up", "condense"], meaning: "요약하다" },
  { word: "relatively", synonyms: ["Comparatively", "by comparison"], meaning: "비교적으로" },
  { word: "Hazard", synonyms: ["Risk", "danger", "peril", "jeopardy"], meaning: "위험" },
  { word: "paramount", synonyms: ["supreme", "prime", "chief"], meaning: "최고의, 중요한" },
  { word: "unwieldy", synonyms: ["Difficult to manage", "awkward"], meaning: "(크기, 무게 때문에) 다루기 힘든" },
  { word: "subsequent", synonyms: ["Succeeding", "following", "later", "following in time"], meaning: "그 다음의" },
  { word: "Striking", synonyms: ["Noticeable", "remarkable", "attention-getting"], meaning: "현저한" },
  { word: "extended", synonyms: ["Long-lasting", "prolonged"], meaning: "장기간에 걸친" },
  { word: "ephemeral", synonyms: ["Short-lived", "living for a short time", "temporary"], meaning: "단명하는, 덧없는" },
  { word: "Rigid", synonyms: ["Strict", "exact", "severe", "rigorous", "stiff", "hard", "firm"], meaning: "엄격한; 굳은, 경직된" },
  { word: "Chief", synonyms: ["Major", "main", "principal", "primary"], meaning: "주요한" },
  { word: "severity", synonyms: ["Seriousness"], meaning: "심함" },
  { word: "typical of", synonyms: ["Characteristic of", "representative of"], meaning: "~을 대표하는" },
  { word: "Enable", synonyms: ["Allow", "permit", "facilitate"], meaning: "가능하게 하다" },
  { word: "empirical", synonyms: ["Based on observation", "experimental"], meaning: "실험상의, 실험에 의한" },
  { word: "controversy", synonyms: ["Dispute", "debate", "disagreement", "contention"], meaning: "논쟁" },
  { word: "accomplish", synonyms: ["Achieve", "execute", "work out", "put together"], meaning: "성취하다" },
  { word: "Set", synonyms: ["Fixed", "settled", "situate", "place", "put"], meaning: "고정된; 놓다" },
  { word: "Lag", synonyms: ["Delay"], meaning: "지연" },
  { word: "Exude", synonyms: ["Give off", "release", "emit"], meaning: "(액체, 냄새 등을) 발산하다" },
  { word: "interplay", synonyms: ["Interaction", "reciprocity"], meaning: "상호작용" },
  { word: "precede", synonyms: ["Come before", "antecede", "forerun"], meaning: "~에 앞서다" },
  { word: "manipulate", synonyms: ["Deliberate alteration"], meaning: "조작" },
  { word: "Dry", synonyms: ["Arid", "rainless", "parched"], meaning: "건조한" },
  { word: "assist with", synonyms: ["Help with", "aid", "support"], meaning: "~을 돕다" },
  { word: "Acute", synonyms: ["Severe", "intense", "extreme"], meaning: "극심한" },
  { word: "Article", synonyms: ["Object", "item", "thing"], meaning: "물품" },
  { word: "scrutiny", synonyms: ["Close observation", "examination", "inspection"], meaning: "정밀 검사" },
  { word: "recompense", synonyms: ["Repayment", "compensation"], meaning: "보상" },
  { word: "reflect", synonyms: ["Show", "indicate", "display", "demonstrate", "meditate", "think", "consider", "ponder"], meaning: "나타내다; 숙고하다" },
  { word: "immeasurably", synonyms: ["Greatly", "extremely"], meaning: "대단히" },
  { word: "rudiments", synonyms: ["Basics", "elements", "fundamentals"], meaning: "기초, 기본" },
  { word: "mortality", synonyms: ["Death"], meaning: "사망" },
  { word: "awkward", synonyms: ["Clumsy", "unskillful"], meaning: "서투른" },
  { word: "constrain", synonyms: ["oblige", "bind", "force", "pressure", "inhibit", "restrain", "restrict"], meaning: "강요하다; 억제하다" },
  { word: "turmoil", synonyms: ["Unrest", "agitation", "stir"], meaning: "소란, 동요" },
  { word: "property", synonyms: ["Characteristic", "character", "quality", "estate", "possession", "havings"], meaning: "특성; 재산" },
  { word: "Fuel", synonyms: ["Give energy to", "encourage"], meaning: "연료를 공급하다; 자극하다" },
  { word: "majestic", synonyms: ["Magnificent", "grand", "august"], meaning: "위엄 있는, 웅대한" },
  { word: "preeminent", synonyms: ["Outstanding", "distinguished", "foremost"], meaning: "뛰어난" },
  { word: "Crude", synonyms: ["Rough", "primitive", "raw", "unrefined"], meaning: "가공하지 않은" },
  { word: "Variety", synonyms: ["Diversity", "multiplicity", "type", "species", "sort", "kind"], meaning: "다양성; 종류" },
  { word: "typically", synonyms: ["Usually", "normally", "ordinarily"], meaning: "보통" },
  { word: "supplementary", synonyms: ["Additional", "extra"], meaning: "추가의" },
  { word: "Reduce", synonyms: ["Decrease", "diminish", "cut"], meaning: "감소시키다" },
  { word: "subject", synonyms: ["Participant", "expose"], meaning: "피실험자; (싫은 일 등을) 겪게 하다" },
  { word: "Flee", synonyms: ["Run away from", "escape", "abscond"], meaning: "도망치다, 벖어나다" },
];

const day8Words = [
  { word: "furthermore", synonyms: ["In addition", "moreover"], meaning: "게다가" },
  { word: "proliferate", synonyms: ["Multiply", "become numerous", "increase in number"], meaning: "증식하다" },
  { word: "Assess", synonyms: ["Evaluate", "estimate", "judge", "appraise"], meaning: "평가하다" },
  { word: "Spur", synonyms: ["Stimulus", "incitement", "incentive", "stimulate", "prompt"], meaning: "자극; 자극하다" },
  { word: "eclectic", synonyms: ["diverse", "various", "manifold"], meaning: "(취미, 의견 등이) 폭넓은, 다방면의" },
  { word: "Crucial", synonyms: ["decisive", "important", "essential", "vital", "acute"], meaning: "결정적인, 중대한" },
  { word: "intricate", synonyms: ["Complex", "complicated", "elaborate", "tangled"], meaning: "복잡한" },
  { word: "palatial", synonyms: ["Magnificent", "grand", "majestic", "splendid"], meaning: "웅장한, 대궐 같은" },
  { word: "Potent", synonyms: ["Powerful", "influential", "strong"], meaning: "(영향 등이) 강력한" },
  { word: "Extract", synonyms: ["Draw", "derive", "remove"], meaning: "끌어내다, 뽑아내다" },
  { word: "Course through", synonyms: ["Run through"], meaning: "~속을 흐르다" },
  { word: "criterion", synonyms: ["Standard", "measure", "norm"], meaning: "기준" },
  { word: "Enjoy", synonyms: ["experience"], meaning: "재미를 보다, 즐겁게 경험하다" },
  { word: "inadvertently", synonyms: ["Unintentionally", "accidentally", "unwittingly"], meaning: "무심코" },
  { word: "Peril", synonyms: ["Danger", "jeopardy", "hazard"], meaning: "위험" },
  { word: "arduous", synonyms: ["Difficult", "strenuous", "laborious"], meaning: "힘든" },
  { word: "Feat", synonyms: ["Achievement", "accomplishment", "exploit"], meaning: "위업" },
  { word: "Friction", synonyms: ["Conflict", "clash", "discord", "strife"], meaning: "마찬, 불화" },
  { word: "materialize", synonyms: ["Appear", "emerge", "loom"], meaning: "나타나다" },
  { word: "regulate", synonyms: ["Adjust", "control"], meaning: "조절하다" },
  { word: "demise", synonyms: ["End", "fall", "collapse", "downfall"], meaning: "종말, 몰락" },
  { word: "Frankly", synonyms: ["Honestly", "openly", "truthfully", "candidly"], meaning: "솔직히" },
  { word: "immensely", synonyms: ["Extremely", "excessively", "enormously", "incredibly"], meaning: "굉장히" },
  { word: "Deem", synonyms: ["Consider", "regard", "believe"], meaning: "생각하다, 여기다" },
  { word: "consumption", synonyms: ["Use", "utilization"], meaning: "소비, 소모" },
  { word: "suspend", synonyms: ["Hang", "dangle", "swing"], meaning: "매달다" },
  { word: "prevent", synonyms: ["Preclude", "avoid", "impede", "avert"], meaning: "막다, 방해하다" },
  { word: "authentic", synonyms: ["Genuine", "true", "real"], meaning: "진짜의" },
  { word: "redundant", synonyms: ["Superfluous", "unnecessary", "wordy", "repetitious"], meaning: "불필요한; 장황한" },
  { word: "profuse", synonyms: ["Abundant", "plentiful", "copious", "lavish"], meaning: "풍부한" },
  { word: "ornament", synonyms: ["Decorate", "adorn", "embellish"], meaning: "장식하다" },
  { word: "demolish", synonyms: ["Destroy", "wreck"], meaning: "파괴하다" },
  { word: "voracious", synonyms: ["Insatiable", "greedy", "gluttonous"], meaning: "만족할 줄 모르는, 탐욕적인" },
  { word: "As well as", synonyms: ["In addition to", "not to mention"], meaning: "~뿐만 아니라" },
  { word: "extreme", synonyms: ["Intense", "severe", "excessive"], meaning: "극심한; 지나친" },
  { word: "Reform", synonyms: ["Betterment", "amend", "improve", "ameliorate"], meaning: "개혁, 개선; 개선하다, 개정하다" },
  { word: "determinant", synonyms: ["Cause", "factor"], meaning: "결정 요인" },
  { word: "inclination", synonyms: ["Tendency", "trend", "preference", "taste"], meaning: "경향; 기호" },
  { word: "inflation", synonyms: ["Expansion", "swelling", "enlargement"], meaning: "팽창" },
  { word: "Routine", synonyms: ["Ordinary", "normal", "conventional"], meaning: "틀에 박힌, 평범한" },
  { word: "accessible", synonyms: ["Reachable", "able to be reached", "obtainable"], meaning: "접근할 수 있는; 얻을 수 있는" },
  { word: "constituent", synonyms: ["Component", "elemental"], meaning: "구성 요소의" },
  { word: "insolent", synonyms: ["Impertinent", "impudent", "rude"], meaning: "무례한" },
  { word: "to be sure", synonyms: ["Certainly", "definitely", "surely"], meaning: "틀림없이" },
  { word: "broadly", synonyms: ["Generally", "mostly"], meaning: "대체로" },
  { word: "Echo", synonyms: ["Reflect", "resound", "resonate", "imitate", "repeat", "reiterate"], meaning: "울리다, 반향하다; 흉내 내다; (말 등을) 되풀이하다" },
  { word: "shoddy", synonyms: ["Inferior", "poor"], meaning: "질이 떨어지는" },
  { word: "Gear", synonyms: ["Adjust", "adapt", "change"], meaning: "맞게 조정하다" },
  { word: "Absorb", synonyms: ["Take in", "imbibe", "soak up"], meaning: "흡수하다" },
  { word: "whereby", synonyms: ["Through which", "by which"], meaning: "(그것에 의하여) ~하는" },
  { word: "assemble", synonyms: ["Gather together", "bring together", "collect"], meaning: "모으다" },
  { word: "liberate", synonyms: ["Free", "release", "loosen"], meaning: "해방하다" },
  { word: "rational", synonyms: ["Logical", "sensible", "reasonable"], meaning: "합리적인" },
  { word: "resistance", synonyms: ["Opposition", "objection", "refusal to accept"], meaning: "반대, 저항" },
  { word: "Indefinite period", synonyms: ["A period whose end has not been determined"], meaning: "무기한" },
  { word: "Ardent", synonyms: ["Enthusiastic", "passionate", "fervent"], meaning: "열렬한" },
  { word: "Extinct", synonyms: ["Having died out", "defunct"], meaning: "멸종된" },
  { word: "be accompanied by", synonyms: ["Occur together with"], meaning: "~와 동반하다" },
  { word: "overestimated", synonyms: ["Bigger than actual value"], meaning: "과대평가된" },
];

const day9Words = [
  { word: "Initiate", synonyms: ["Start", "begin", "originate", "advance", "commence"], meaning: "시작하다" },
  { word: "tremendous", synonyms: ["Great", "large", "huge", "gigantic"], meaning: "엄청난" },
  { word: "breakthrough", synonyms: ["(sudden) progress"], meaning: "큰 발전" },
  { word: "Cope with", synonyms: ["Deal with", "handle", "manage"], meaning: "~에 대처하다, ~를 다루다" },
  { word: "inducement", synonyms: ["Incentive", "incitement", "lure"], meaning: "유인(책), 장려" },
  { word: "irreversible", synonyms: ["Irreparable", "irremediable", "irrevocable"], meaning: "돌이킬 수 없는" },
  { word: "comprise", synonyms: ["Include", "encompass", "consist of", "be made up of", "be composed of"], meaning: "포함하다; ~으로 구성되다" },
  { word: "culmination", synonyms: ["High point", "apex", "pinnacle"], meaning: "장점, 최고조" },
  { word: "allegiance", synonyms: ["Loyalty", "fidelity", "commitment", "dedication"], meaning: "충성, 헌신" },
  { word: "notable", synonyms: ["Remarkable", "outstanding", "important"], meaning: "주목할 만한, 중요한" },
  { word: "idiosyncrasy", synonyms: ["Peculiarity", "eccentricity", "oddity"], meaning: "특징, 이상한 점" },
  { word: "Minute", synonyms: ["Tiny", "very small", "diminutive"], meaning: "아주 작은" },
  { word: "markedly", synonyms: ["Significantly", "noticeably", "considerably", "substantially"], meaning: "현저하게" },
  { word: "phenomenon", synonyms: ["Occurrence", "incident"], meaning: "현상, 사건" },
  { word: "disseminate", synonyms: ["Spread", "disperse", "distribute"], meaning: "퍼뜨리다" },
  { word: "Current", synonyms: ["Present", "existing"], meaning: "현재의" },
  { word: "Detrimental", synonyms: ["Harmful", "injurious", "damaging", "pernicious"], meaning: "해로운" },
  { word: "presume", synonyms: ["Believe", "accept as true"], meaning: "~라고 생각하다, 추정하다" },
  { word: "anarchy", synonyms: ["disorder", "chaos", "disorganization"], meaning: "무질서, 혼란" },
  { word: "Snake", synonyms: ["wind", "meander", "curve", "twist"], meaning: "구불구불 가다" },
  { word: "sophisticated", synonyms: ["complex", "highly developed"], meaning: "정교한, 고도로 발달한" },
  { word: "Derive", synonyms: ["originate", "trace", "obtain", "gain"], meaning: "유래하다; 얻다" },
  { word: "Sole", synonyms: ["only", "single", "solitary"], meaning: "유일한" },
  { word: "embellish", synonyms: ["decorate", "make attractive", "adorn", "beautify", "ornament"], meaning: "장식하다" },
  { word: "antagonize", synonyms: ["anger", "aggravate", "counteract"], meaning: "~의 반감을 사다; 대항하다" },
  { word: "Yearn", synonyms: ["long", "desire", "crave", "pine"], meaning: "갈망하다" },
  { word: "Permit", synonyms: ["allow", "let", "approve"], meaning: "허락하다" },
  { word: "scarcity", synonyms: ["lack", "shortage", "insufficiency", "deficiency"], meaning: "부족" },
  { word: "renounce", synonyms: ["give up", "reject", "relinquish"], meaning: "포기하다, 버리다" },
  { word: "keep in check", synonyms: ["limit", "control", "restrict", "restrain"], meaning: "제어하다, 억제하다" },
  { word: "subsistence", synonyms: ["survival", "existence", "living"], meaning: "생존" },
  { word: "annually", synonyms: ["each year", "yearly", "every year"], meaning: "매년" },
  { word: "emerge", synonyms: ["appear", "loom", "spring up", "come out", "develop"], meaning: "나타나다" },
  { word: "customary", synonyms: ["habitual", "traditional", "typical", "accustomed"], meaning: "습관적인, 관례적인" },
  { word: "Widely", synonyms: ["extensively", "broadly"], meaning: "널리" },
  { word: "Assign", synonyms: ["specify", "designate", "appoint"], meaning: "지정하다" },
  { word: "equivocal", synonyms: ["ambiguous", "vague", "obscure", "uncertain"], meaning: "모호한" },
  { word: "Release", synonyms: ["free", "liberate", "loose", "emit", "give off", "discharge", "exude"], meaning: "석방하다; 방출하다" },
  { word: "essentially", synonyms: ["basically", "fundamentally", "primarily"], meaning: "기본적으로, 본질적으로" },
  { word: "oversee", synonyms: ["supervise", "control", "superintend"], meaning: "감독하다" },
  { word: "Rapidly", synonyms: ["quickly", "fast"], meaning: "급속한, 빨리" },
  { word: "acknowledge", synonyms: ["recognize", "admit", "accept"], meaning: "인정하다" },
  { word: "Rough", synonyms: ["uneven", "rugged", "bumpy", "coarse"], meaning: "울퉁불퉁한, 거친" },
  { word: "preclude", synonyms: ["prevent", "stop", "hinder", "rule out", "exclude"], meaning: "막다; 배제하다" },
  { word: "portable", synonyms: ["able to be carried", "mobile", "movable"], meaning: "휴대용의" },
  { word: "presumable", synonyms: ["probable", "likely", "possible"], meaning: "그럴듯한, 있음직한" },
  { word: "calculatedly", synonyms: ["deliberately", "intentionally", "knowingly"], meaning: "계획적으로" },
  { word: "deviation", synonyms: ["departure", "divergence", "aberration"], meaning: "일탈" },
  { word: "Hairline", synonyms: ["slight", "thin"], meaning: "아주 가느다란" },
  { word: "formulate", synonyms: ["develop", "devise", "forge", "state", "specify", "express"], meaning: "고안하다, 발전시키다; 명확히 말하다" },
  { word: "Astute", synonyms: ["insightful", "shrewd", "clever", "sharp"], meaning: "통찰력 있는; 영악한" },
  { word: "reliable", synonyms: ["dependable", "trustworthy", "credible"], meaning: "신뢰할 수 있는" },
  { word: "take precedence over", synonyms: ["be more important than", "come before"], meaning: "~보다 우선하다" },
  { word: "allusion", synonyms: ["reference", "mention", "implication", "suggestion"], meaning: "(간접적인) 언급, 암시" },
  { word: "locomotion", synonyms: ["movement", "motion"], meaning: "이동 능력" },
  { word: "principally", synonyms: ["mainly"], meaning: "주로" },
  { word: "rebellion", synonyms: ["uprising", "revolt"], meaning: "반란" },
  { word: "Revive", synonyms: ["recover"], meaning: "회복하다, 소생하다" },
];

const day10Words = [
  { word: "Modify", synonyms: ["change", "alter", "adjust", "adapt"], meaning: "바꾸다, 조정하다" },
  { word: "Initially", synonyms: ["at first", "originally", "primarily"], meaning: "처음에" },
  { word: "Critical", synonyms: ["(most) important", "crucial", "essential", "dangerous", "risky"], meaning: "중요한; 위독한, 위험한" },
  { word: "luminous", synonyms: ["brilliant", "bright", "shining", "glowing"], meaning: "빛나는" },
  { word: "facilitate", synonyms: ["ease", "make easy", "help", "assist", "aid"], meaning: "용이하게 하다" },
  { word: "refinement", synonyms: ["small improvement", "advancement", "enhancement"], meaning: "개선" },
  { word: "attribute", synonyms: ["characteristic", "trait", "quality", "property", "ascribe", "credit", "impute", "refer"], meaning: "특성; ~의 탓(덕)으로 돌리다" },
  { word: "Belch", synonyms: ["suddenly emit", "discharge", "erupt", "vent"], meaning: "분출하다" },
  { word: "underrate", synonyms: ["undervalue", "underestimate", "belittle"], meaning: "과소평가하다" },
  { word: "immense", synonyms: ["large", "enormous", "huge", "tremendous"], meaning: "거대한" },
  { word: "Virtue", synonyms: ["goodness", "merit", "desirable quality", "strength"], meaning: "장점" },
  { word: "bustling", synonyms: ["busy", "lively"], meaning: "붐비는, 떠들썩한" },
  { word: "distinct", synonyms: ["different", "separate", "discrete", "definite", "clear and recognizable"], meaning: "다른, 별개의; 뚜렷한" },
  { word: "thriving", synonyms: ["prosperous", "successful", "flourishing"], meaning: "번영하는" },
  { word: "obvious", synonyms: ["evident", "clear", "apparent", "conspicuous"], meaning: "분명한" },
  { word: "exceptional", synonyms: ["extraordinary", "abnormal", "unusual"], meaning: "이례적인" },
  { word: "cumbersome", synonyms: ["difficult to handle", "burdensome", "awkward"], meaning: "다루기 힘든" },
  { word: "boon", synonyms: ["great benefit", "advantage"], meaning: "큰 이익, 혜택" },
  { word: "optimum", synonyms: ["best", "favorable", "most supreme"], meaning: "최고의" },
  { word: "uniformly", synonyms: ["evenly", "regularly", "consistently"], meaning: "균일하게, 한결같이" },
  { word: "unleash", synonyms: ["release", "unloose"], meaning: "(속박을) 풀다" },
  { word: "acquire", synonyms: ["obtain", "gain", "procure", "earn"], meaning: "얻다" },
  { word: "Enigma", synonyms: ["mystery", "puzzle", "riddle"], meaning: "수수께끼" },
  { word: "Steadfast", synonyms: ["unwavering", "firm", "enduring", "resolute"], meaning: "변함없는, 단호한" },
  { word: "Dainty", synonyms: ["delicate", "exquisite", "refined"], meaning: "우아한, 섬세한" },
  { word: "Anomaly", synonyms: ["irregularity", "abnormality", "exception"], meaning: "이례적인 것, 예외" },
  { word: "Splendid", synonyms: ["marvelous", "magnificent"], meaning: "멋진" },
  { word: "Rapport", synonyms: ["bond", "relationship", "link", "tie"], meaning: "(친밀한) 관계" },
  { word: "Question", synonyms: ["take a critical look at", "dispute"], meaning: "~에 대해 이의를 제기하다" },
  { word: "scatter", synonyms: ["disperse", "distribute", "dissipate", "spread out", "widely spread"], meaning: "흩뿌리다" },
  { word: "Escalate", synonyms: ["intensify", "increase", "mount", "rise"], meaning: "확대되다, 증대하다" },
  { word: "Temporary", synonyms: ["short-lived", "makeshift", "for a limited time", "transitory"], meaning: "일시적인" },
  { word: "Attest", synonyms: ["confirm", "support", "prove"], meaning: "증명하다, 입증하다" },
  { word: "Fortify", synonyms: ["strengthen", "reinforce"], meaning: "강화하다" },
  { word: "Remove", synonyms: ["eliminate", "extract", "withdraw"], meaning: "제거하다" },
  { word: "End", synonyms: ["purpose", "goal", "aim"], meaning: "목적, 목표" },
  { word: "Plentiful", synonyms: ["abundant", "bountiful", "rich"], meaning: "풍부한" },
  { word: "make it", synonyms: ["arrive"], meaning: "(제시간에) 도착하다" },
  { word: "Devastate", synonyms: ["destroy", "demolish", "ravage", "ruin"], meaning: "완전히 파괴하다" },
  { word: "Eminently", synonyms: ["exceptionally", "highly", "extremely"], meaning: "대단히, 현저히" },
  { word: "subtraction", synonyms: ["decrease", "deduction", "reduction"], meaning: "삭감, 공제" },
  { word: "as a rule of thumb", synonyms: ["in general"], meaning: "경험적으로 보아 대개" },
  { word: "Blur", synonyms: ["make less distinct", "obscure", "cloud"], meaning: "흐리게 하다" },
  { word: "Relay", synonyms: ["transfer", "communicate", "transmit", "impart"], meaning: "전달하다" },
  { word: "expandable", synonyms: ["able to be enlarged", "extendable"], meaning: "펼칠 수 있는, 확장할 수 있는" },
  { word: "Scrupulous", synonyms: ["careful", "fastidious", "meticulous", "honest", "moral"], meaning: "세심한, 꼼꼼한; 양심적인" },
  { word: "Approximately", synonyms: ["about", "roughly", "nearly"], meaning: "대략" },
  { word: "Paradoxical", synonyms: ["seemingly contradictory", "ironic"], meaning: "역설적인" },
  { word: "Source", synonyms: ["origin", "beginning", "derivation"], meaning: "근원, 기원" },
  { word: "Adhere", synonyms: ["stick", "cleave", "cling"], meaning: "부착되다, 달라붙다" },
  { word: "Available", synonyms: ["accessible", "obtainable"], meaning: "구할 수 있는" },
  { word: "get rid of", synonyms: ["eliminate", "remove", "dispose of"], meaning: "~을 없애다" },
  { word: "Repel", synonyms: ["drive away", "beat off"], meaning: "물리치다" },
  { word: "Maximize", synonyms: ["increase to the greatest possible degree"], meaning: "극대화하다" },
  { word: "Outermost", synonyms: ["farthest away", "farthest", "most remote"], meaning: "가장 바깥의" },
  { word: "Bind", synonyms: ["fasten"], meaning: "묶다" },
  { word: "Visible", synonyms: ["perceptible"], meaning: "눈에 띄는, 명백한" },
];
