const day11Words = [
  { word: "Plausible", synonyms: ["possible", "believable", "likely", "probable"], meaning: "그럴듯한" },
  { word: "Transform", synonyms: ["convert", "change", "alter"], meaning: "변형시키다, 바꾸다" },
  { word: "Counterpart", synonyms: ["complement", "equivalent"], meaning: "(쌍을 이루는) 한쪽; 동등한 것" },
  { word: "Nevertheless", synonyms: ["in spite of that", "however", "still", "yet", "nonetheless"], meaning: "그럼에도 불구하고" },
  { word: "Pronounced", synonyms: ["notable", "striking", "marked", "significant", "noticeable", "distinct", "strong"], meaning: "현저한" },
  { word: "Celebrated", synonyms: ["famous", "renowned", "well-known"], meaning: "유명한" },
  { word: "Exceedingly", synonyms: ["highly", "extremely", "excessively", "hugely"], meaning: "대단히" },
  { word: "Chancy", synonyms: ["risky", "perilous", "dangerous"], meaning: "위험한" },
  { word: "Vertical", synonyms: ["upright", "up-and-down"], meaning: "수직의" },
  { word: "Persist", synonyms: ["continue", "last", "endure", "remain"], meaning: "지속되다" },
  { word: "Magnitude", synonyms: ["extent", "size", "degree", "measure", "amount"], meaning: "규모, 정도" },
  { word: "Discern", synonyms: ["detect", "identify", "distinguish"], meaning: "파악하다, 알아내다" },
  { word: "Generate", synonyms: ["produce", "create"], meaning: "만들어 내다" },
  { word: "Eccentric", synonyms: ["unusual", "bizarre", "peculiar", "odd"], meaning: "별난, 특이한" },
  { word: "Alternative", synonyms: ["substitutive", "different", "substituted", "choice", "option"], meaning: "대안이 되는; 다른; 대안" },
  { word: "Strategy", synonyms: ["plan", "method", "scheme"], meaning: "전략, 방법" },
  { word: "Refine", synonyms: ["improve", "perfect"], meaning: "개선하다" },
  { word: "Precious", synonyms: ["valuable", "dear", "priceless"], meaning: "귀중한" },
  { word: "Subtle", synonyms: ["hard to recognize", "hardly perceived", "slight"], meaning: "미묘한, 감지하기 어려운" },
  { word: "favorable to", synonyms: ["helpful for", "conducive to", "beneficial to"], meaning: "~에 도움이 되는" },
  { word: "preoccupied with", synonyms: ["concentrated on", "absorbed in", "immersed in"], meaning: "~에 몰두한" },
  { word: "Swift", synonyms: ["quick", "speedy", "fleet"], meaning: "재빠른" },
  { word: "Menace", synonyms: ["threaten", "intimidate", "frighten"], meaning: "위협하다" },
  { word: "akin to", synonyms: ["similar to", "like"], meaning: "~과 유사한" },
  { word: "Expend", synonyms: ["use", "use up", "spend", "consume"], meaning: "(시간, 에너지 등을) 쓰다" },
  { word: "Belittle", synonyms: ["disregard", "underestimate"], meaning: "경시하다" },
  { word: "Commend", synonyms: ["admire", "praise", "compliment"], meaning: "칭찬하다" },
  { word: "Sue", synonyms: ["take legal action against", "charge"], meaning: "고소하다" },
  { word: "Innovation", synonyms: ["new development", "novelty", "new idea"], meaning: "혁신, 새로 도입한 것" },
  { word: "fragmentation", synonyms: ["destruction", "disintegration", "disruption"], meaning: "붕괴, 분열" },
  { word: "Mainly", synonyms: ["principally", "generally", "primarily", "chiefly"], meaning: "주로" },
  { word: "Sufficient", synonyms: ["enough", "adequate", "ample"], meaning: "충분한" },
  { word: "Abnormally", synonyms: ["unusually", "oddly", "exceptionally", "atypically"], meaning: "이례적으로, 이상하게" },
  { word: "Barrier", synonyms: ["bar", "obstacle", "obstruction"], meaning: "장벽, 장애물" },
  { word: "Gigantic", synonyms: ["huge", "immense", "colossal"], meaning: "거대한" },
  { word: "Reproduce", synonyms: ["copy", "duplicate", "imitate", "breed", "multiply", "propagate"], meaning: "복제하다, 모사하다; 번식하다" },
  { word: "Allow", synonyms: ["enable", "permit", "let"], meaning: "허락하다" },
  { word: "Penetrate", synonyms: ["pierce", "go through", "enter"], meaning: "꿰뚫다" },
  { word: "Device", synonyms: ["mechanism", "apparatus", "appliance"], meaning: "장치, 기구" },
  { word: "Divergent", synonyms: ["different", "varying", "dissimilar"], meaning: "(의견 등이) 다른, 갈라지는" },
  { word: "Flaw", synonyms: ["defect", "fault", "blemish", "shortcoming"], meaning: "결점" },
  { word: "Buffer", synonyms: ["protect", "cushion"], meaning: "(충격을) 완화하다, 보호하다" },
  { word: "Refuse", synonyms: ["disprove", "rebut", "prove false"], meaning: "논박하다" },
  { word: "Domestic", synonyms: ["household", "home", "family"], meaning: "가정의" },
  { word: "on the spur of the moment", synonyms: ["without planning", "on impulse"], meaning: "충동적으로" },
  { word: "Temperate", synonyms: ["moderate", "mild", "clement"], meaning: "(기후 등이) 온화한" },
  { word: "consistent with", synonyms: ["in agreement with", "congruent with"], meaning: "~과 일치하는" },
  { word: "Splendor", synonyms: ["magnificence", "grandeur", "majesty"], meaning: "장려함, 화려함" },
  { word: "Prosper", synonyms: ["succeed", "flourish", "thrive"], meaning: "번창하다, 성공하다" },
  { word: "Brew", synonyms: ["develop", "loom", "be on the way"], meaning: "일어나려고 하다" },
  { word: "Persevere", synonyms: ["continue", "carry on", "persist"], meaning: "인내하며 계속하다" },
  { word: "Bias", synonyms: ["Prejudice"], meaning: "편견" },
  { word: "Administer", synonyms: ["manage", "supervise", "conduct", "give", "provide"], meaning: "관리하다; (약 등을) 복용하다, 투여하다" },
  { word: "Groundless", synonyms: ["unfounded", "baseless"], meaning: "근거 없는" },
  { word: "Arouse", synonyms: ["stimulate", "provoke", "incite"], meaning: "자극하다" },
  { word: "Occupy", synonyms: ["engross", "engage", "absorb"], meaning: "(주의, 마음을) 끌다" },
  { word: "Virtual", synonyms: ["almost complete"], meaning: "거의 ~과 다름없는, 사실상의" },
  { word: "Unexplored", synonyms: ["Uncovered"], meaning: "탐사되지 않은, 논의되지 않은" },
  { word: "turned to", synonyms: ["in agreement with"], meaning: "~과 일치한" },
];

const day12Words = [
  { word: "Duration", synonyms: ["span", "length", "term"], meaning: "(지속되는) 기간" },
  { word: "Massive", synonyms: ["huge", "large", "enormous", "tremendous", "colossal"], meaning: "대규모의, 거대한" },
  { word: "Feasible", synonyms: ["practicable", "viable", "possible", "achievable", "most likely"], meaning: "실행 가능한" },
  { word: "Vibrant", synonyms: ["active", "vivacious", "energetic", "vivid", "bright", "brilliant"], meaning: "활기 넘치는; (색 등이) 선명한" },
  { word: "Accumulation", synonyms: ["buildup", "collection", "stock"], meaning: "축적" },
  { word: "Link", synonyms: ["connection", "bond", "tie", "connect", "relate", "associate"], meaning: "관대, 유대; 관련짓다" },
  { word: "Informally", synonyms: ["commonly", "casually"], meaning: "비공식적으로" },
  { word: "Sovereign", synonyms: ["master", "monarch", "ruler"], meaning: "군주" },
  { word: "Key", synonyms: ["important", "central", "essential", "tone"], meaning: "중요한; (악곡의) 조" },
  { word: "Eventually", synonyms: ["in the end", "ultimately", "later", "in due time"], meaning: "결국" },
  { word: "Persistent", synonyms: ["continuous", "enduring", "long-lasting", "constant"], meaning: "지속되는" },
  { word: "Corroborate", synonyms: ["confirm", "verify", "substantiate"], meaning: "확증하다" },
  { word: "inaugurate", synonyms: ["introduce", "initiate", "begin", "commence"], meaning: "개시하다, 시작하다" },
  { word: "further", synonyms: ["additional", "extra", "supplementary"], meaning: "추가적인" },
  { word: "concentrate on", synonyms: ["focus on", "pay attention to"], meaning: "~에 집중하다" },
  { word: "moreover", synonyms: ["additionally", "in addition", "as well", "besides"], meaning: "게다가" },
  { word: "execute", synonyms: ["perform", "carry out", "fulfill", "implement", "produce"], meaning: "수행하다; (미술품 등을) 제작하다" },
  { word: "urbane", synonyms: ["cultivated", "sophisticated", "polished", "refined"], meaning: "세련된" },
  { word: "boast", synonyms: ["show off", "brag", "swagger", "pride oneself on", "proudly possess"], meaning: "자랑하다; (자랑거리로서) 가지고 있다" },
  { word: "envision", synonyms: ["imagine", "conceive", "visualize"], meaning: "마음속에 그리다, 상상하다" },
  { word: "intermediate", synonyms: ["in-between", "between extremes", "median"], meaning: "중간의" },
  { word: "frightful", synonyms: ["alarming", "fearsome"], meaning: "무서운" },
  { word: "irrevocable", synonyms: ["permanent", "irreversible", "unchangeable"], meaning: "돌이킬 수 없는" },
  { word: "disintegration", synonyms: ["breaking apart", "collapse"], meaning: "분해, 붕괴" },
  { word: "burgeoning", synonyms: ["rapidly expanding", "growing", "escalating"], meaning: "급증하는" },
  { word: "terrestrial", synonyms: ["earthly", "worldly"], meaning: "속세의" },
  { word: "adorn", synonyms: ["decorate", "beautify", "ornament"], meaning: "꾸미다" },
  { word: "revolution", synonyms: ["fundamental innovation", "change"], meaning: "변혁, 개혁" },
  { word: "randomness", synonyms: ["lack of pattern"], meaning: "무작위성" },
  { word: "superficial", synonyms: ["external", "not deep", "exterior"], meaning: "표면적인" },
  { word: "diversion", synonyms: ["Distraction"], meaning: "주위 전환들" },
  { word: "originate from", synonyms: ["come from", "derive from", "stem from"], meaning: "~에서 비롯되다" },
  { word: "intimate", synonyms: ["close", "familiar"], meaning: "친밀한" },
  { word: "blossom", synonyms: ["flourish", "bloom", "thrive"], meaning: "번영하다" },
  { word: "groundwork", synonyms: ["foundation", "basis", "footing"], meaning: "토대, 기초" },
  { word: "trivial", synonyms: ["small", "frivolous", "unimportant", "insignificant"], meaning: "사소한" },
  { word: "posterity", synonyms: ["future generations", "next generations"], meaning: "후대" },
  { word: "aggravate", synonyms: ["make worse", "worsen", "exacerbate"], meaning: "악화시키다" },
  { word: "obtainable", synonyms: ["available", "accessible", "attainable"], meaning: "얻을 수 있는" },
  { word: "extent", synonyms: ["range", "scope", "stretch"], meaning: "범위" },
  { word: "ingenious", synonyms: ["inventive", "creative", "innovative", "clever"], meaning: "기발한, 독창적인" },
  { word: "burst", synonyms: ["break open", "break out"], meaning: "터지다" },
  { word: "outlying", synonyms: ["far from the center", "remote", "distant"], meaning: "외진, 중심에서 떨어진" },
  { word: "revolve around", synonyms: ["focus on", "center on"], meaning: "~을 중심으로 돈다" },
  { word: "meticulously", synonyms: ["carefully", "precisely"], meaning: "꼼꼼히" },
  { word: "utilitarian", synonyms: ["practical", "pragmatic", "functional"], meaning: "실용적인" },
  { word: "constitute", synonyms: ["make up", "comprise", "compose"], meaning: "구성하다" },
  { word: "reciprocal", synonyms: ["Mutual"], meaning: "상호 간의" },
  { word: "tendency", synonyms: ["inclination", "trend", "proneness"], meaning: "경향" },
  { word: "artifact", synonyms: ["object", "item", "article"], meaning: "인공 유물" },
  { word: "expedite", synonyms: ["accelerate", "speed up", "urge", "rush"], meaning: "신속히 처리하다, 촉진시키다" },
  { word: "scenario", synonyms: ["situation", "sequence of events"], meaning: "(사건의) 시나리오" },
  { word: "define", synonyms: ["Identify"], meaning: "분명히 하다" },
  { word: "propulsion", synonyms: ["moving forward", "thrust", "impetus"], meaning: "추진, 추진력" },
  { word: "resolute", synonyms: ["firm", "determined", "steadfast", "unwavering"], meaning: "확고한" },
  { word: "phase", synonyms: ["period", "stage", "step"], meaning: "시기, 단계" },
  { word: "fairly", synonyms: ["reasonably", "moderately", "pretty", "impartially"], meaning: "꽤; 공정하게" },
];

const day13Words = [
  { word: "merely", synonyms: ["simply", "only", "no more than", "just", "purely"], meaning: "단지" },
  { word: "decimate", synonyms: ["destroy", "eliminate", "wipe out", "demolish", "devastate"], meaning: "(많은 사람을) 죽이다" },
  { word: "incentive", synonyms: ["motivation", "motive", "encouragement", "inducement"], meaning: "동기, 자극" },
  { word: "retrieve", synonyms: ["bring back", "get back", "recover", "obtain", "regain"], meaning: "되찾다" },
  { word: "compress", synonyms: ["condense", "compact", "contract", "crush"], meaning: "압축하다" },
  { word: "designate", synonyms: ["indicate", "identify", "specify", "define"], meaning: "명시하다" },
  { word: "dissemination", synonyms: ["spread", "distribution", "diffusion"], meaning: "보급, 유포" },
  { word: "marked", synonyms: ["noticeable", "considerate", "prominent", "discernible"], meaning: "두드러진, 현저한" },
  { word: "hypothetical", synonyms: ["supposed", "imaginary"], meaning: "가상의, 가정의" },
  { word: "flow", synonyms: ["stream", "current", "movement", "motion"], meaning: "흐름; 이동" },
  { word: "precise", synonyms: ["exact", "accurate", "definite"], meaning: "정확한" },
  { word: "stipulate", synonyms: ["require", "demand", "call for"], meaning: "(조건으로서) 요구하다" },
  { word: "perspective", synonyms: ["point of view", "viewpoint", "orientation"], meaning: "관점" },
  { word: "enhance", synonyms: ["improve", "enrich", "intensify"], meaning: "향상시키다" },
  { word: "fundamental", synonyms: ["essential", "basic", "primary", "elementary"], meaning: "근본적인, 기본적인" },
  { word: "evident", synonyms: ["clear", "apparent", "obvious", "manifest"], meaning: "분명한" },
  { word: "shift", synonyms: ["move", "transfer", "change", "switch"], meaning: "옮기다, 바꾸다" },
  { word: "unique among", synonyms: ["different from other"], meaning: "~중에서 유일무이한" },
  { word: "full-fledged", synonyms: ["well-developed", "full-blown"], meaning: "완전히 발달한" },
  { word: "laborious", synonyms: ["difficult", "strenuous"], meaning: "인내를 요하는, 힘든" },
  { word: "emit", synonyms: ["give off", "exhale", "release", "discharge", "send out"], meaning: "내뿜다, 방출하다" },
  { word: "stunning", synonyms: ["amazing", "impressive"], meaning: "눈띨 만큼 멋진" },
  { word: "tantalizing", synonyms: ["tempting", "enticing", "teasing"], meaning: "흥미를 돋우는; 감질나는" },
  { word: "abandoned", synonyms: ["no longer occupied", "deserted", "vacant"], meaning: "버려진" },
  { word: "transmit", synonyms: ["convey", "communicate", "send"], meaning: "전하다" },
  { word: "candidly", synonyms: ["honestly", "frankly", "plainly"], meaning: "솔직히" },
  { word: "compulsorily", synonyms: ["by requirement", "obligatorily", "mandatorily"], meaning: "의무적으로" },
  { word: "aid", synonyms: ["assist", "support", "help", "back"], meaning: "돕다" },
  { word: "deliberation", synonyms: ["debate", "discussion", "conference"], meaning: "토의" },
  { word: "preposterous", synonyms: ["absurd", "unbelievable", "nonsensical"], meaning: "터무니없는" },
  { word: "sparse", synonyms: ["scattered", "thinly distributed", "scanty", "meager", "scarce", "limited"], meaning: "드문드문한; 부족한" },
  { word: "occasionally", synonyms: ["once in a while", "now and then", "sometimes"], meaning: "가끔" },
  { word: "inconceivable", synonyms: ["unthinkable", "unimaginable"], meaning: "상상도 할 수 없는" },
  { word: "breeding", synonyms: ["reproduction", "propagation"], meaning: "번식" },
  { word: "overriding", synonyms: ["dominant", "chief", "principal"], meaning: "가장 중요한" },
  { word: "favor", synonyms: ["prefer", "lean toward"], meaning: "더 좋아하다" },
  { word: "sediment", synonyms: ["remains", "deposition"], meaning: "침전물" },
  { word: "clever", synonyms: ["ingenious", "smart", "brilliant", "bright"], meaning: "영리한" },
  { word: "consistently", synonyms: ["regularly", "typically", "unchangingly"], meaning: "일관되게" },
  { word: "rate", synonyms: ["judge", "assess", "evaluate"], meaning: "평가하다" },
  { word: "predominate", synonyms: ["outweigh", "prevail", "most popular"], meaning: "우세하다; 우세한" },
  { word: "realize", synonyms: ["be aware of", "understand", "catch on", "achieve", "accomplish", "fulfill"], meaning: "깨닫다, 이해하다; 달성하다, 실현하다" },
  { word: "circuitous", synonyms: ["indirect", "roundabout"], meaning: "우회하는" },
  { word: "owing to", synonyms: ["due to", "because of", "as a result of"], meaning: "~때문에" },
  { word: "model", synonyms: ["specimen", "prototype", "example"], meaning: "견본" },
  { word: "with respect to", synonyms: ["with regard to", "in terms of", "in reference to"], meaning: "~에 관하여" },
  { word: "continuous", synonyms: ["uninterrupted", "ongoing", "unceasing", "consecutive"], meaning: "계속되는" },
  { word: "collaborate", synonyms: ["cooperate", "put effort together", "work together"], meaning: "협력하다" },
  { word: "anonymous", synonyms: ["unknown", "unnamed", "unidentified", "innominate"], meaning: "익명의, 신원 불명의" },
  { word: "somewhat", synonyms: ["to some degree", "to some extent", "rather"], meaning: "어느 정도" },
  { word: "damaging", synonyms: ["harmful", "detrimental", "noxious"], meaning: "해로운" },
  { word: "dramatically", synonyms: ["substantially", "greatly", "remarkably"], meaning: "극적으로, 몹시" },
  { word: "heighten", synonyms: ["increase", "intensify"], meaning: "고조시키다" },
  { word: "share", synonyms: ["portion", "part", "allotment"], meaning: "몫" },
  { word: "shortly", synonyms: ["soon", "presently"], meaning: "곧" },
  { word: "besides", synonyms: ["in addition", "moreover", "apart from"], meaning: "게다가; ~외에" },
  { word: "seep", synonyms: ["ooze", "flow slowly", "pass through slowly"], meaning: "스며 나오다" },
  { word: "habit", synonyms: ["usual behavior", "custom", "practice"], meaning: "습관" },
];

const day14Words = [
  { word: "lethal", synonyms: ["deadly", "dangerous", "fatal", "pernicious"], meaning: "치명적인" },
  { word: "modest", synonyms: ["small", "not large", "limited", "simple"], meaning: "크지(많지) 않은; 수수한" },
  { word: "component", synonyms: ["element", "constituent", "ingredient", "part", "factor"], meaning: "구성 요소" },
  { word: "exploitation", synonyms: ["use", "abuse", "misuse"], meaning: "(부당한) 이용, 착취" },
  { word: "relic", synonyms: ["remains", "remnant", "vestige"], meaning: "유물, 나머지" },
  { word: "profoundly", synonyms: ["deeply", "completely", "strongly"], meaning: "깊이; 대단히" },
  { word: "deflect", synonyms: ["change the direction of", "divert"], meaning: "방향을 바꾸다" },
  { word: "highlight", synonyms: ["emphasize", "stress", "underline", "accent"], meaning: "강조하다" },
  { word: "exert", synonyms: ["apply", "exercise", "employ", "put forth", "wield"], meaning: "(힘, 능력 등을) 가하다, 행사하다" },
  { word: "potential", synonyms: ["possible", "prospective", "latent", "possibility"], meaning: "잠재적인; 가능성" },
  { word: "recurring", synonyms: ["repeated", "recurrent"], meaning: "되풀이되는" },
  { word: "meager", synonyms: ["scanty", "scarce", "very low", "deficient"], meaning: "불충분한" },
  { word: "prevail", synonyms: ["be dominant", "dominate", "be widespread", "be prevalent", "triumph"], meaning: "널리 퍼지다, 만연하다; 이기다" },
  { word: "exclusively", synonyms: ["solely", "only", "entirely", "totally"], meaning: "오로지, 전적으로" },
  { word: "consensus", synonyms: ["agreement", "consent"], meaning: "합의" },
  { word: "now and then", synonyms: ["occasionally", "from time to time", "at times"], meaning: "가끔" },
  { word: "discrete", synonyms: ["separate", "distinct", "individual"], meaning: "별개의" },
  { word: "anchor", synonyms: ["hold in place", "secure", "fasten"], meaning: "고정시키다" },
  { word: "improbable", synonyms: ["unlikely", "implausible", "doubtful"], meaning: "있음직하지 않은" },
  { word: "pragmatic", synonyms: ["practical", "utilitarian"], meaning: "실용적인" },
  { word: "undisputed", synonyms: ["acknowledged", "accepted", "recognized"], meaning: "모두가 인정하는" },
  { word: "allocation", synonyms: ["distribution", "assignment", "allotment"], meaning: "할당, 배분" },
  { word: "inconclusive", synonyms: ["not definitive", "indecisive"], meaning: "결정적이지 않은" },
  { word: "withstand", synonyms: ["endure", "resist", "sustain"], meaning: "견디다" },
  { word: "cornerstone", synonyms: ["foundation", "basic element", "basis", "underpinning"], meaning: "토대, 기초" },
  { word: "marvelous", synonyms: ["wonderful", "astonishing", "amazing"], meaning: "놀라운" },
  { word: "clue", synonyms: ["information", "indication", "evidence", "trace", "sign"], meaning: "단서, 증거" },
  { word: "unintentionally", synonyms: ["inadvertently", "accidentally", "unconsciously"], meaning: "의도치 않게" },
  { word: "peak", synonyms: ["height", "pinnacle", "summit", "maximum"], meaning: "정점, 절정" },
  { word: "continual", synonyms: ["constant", "incessant", "ceaseless"], meaning: "끊임없는" },
  { word: "thorough", synonyms: ["complete", "exhaustive", "intensive"], meaning: "철저한" },
  { word: "accurate", synonyms: ["precise", "correct", "exact", "true"], meaning: "정확한" },
  { word: "mobilize", synonyms: ["put into action", "deploy"], meaning: "동원되다" },
  { word: "given that", synonyms: ["accepting that", "considering that"], meaning: "~을 고려하면" },
  { word: "cargo", synonyms: ["shipment", "load", "freight", "burden"], meaning: "화물, 짐" },
  { word: "solitary", synonyms: ["isolated", "secluded", "remote", "alone", "lonely"], meaning: "외딴; 외로운" },
  { word: "slightly", synonyms: ["a little", "somewhat", "a bit"], meaning: "약간" },
  { word: "deliberately", synonyms: ["intentionally", "consciously", "on purpose"], meaning: "일부러" },
  { word: "unthinkable", synonyms: ["inconceivable", "unimaginable"], meaning: "상상도 할 수 없는" },
  { word: "coinage", synonyms: ["creation", "innovation"], meaning: "신조어" },
  { word: "obligation", synonyms: ["responsibility", "duty", "liability"], meaning: "의무, 책임" },
  { word: "reconcile", synonyms: ["bring together", "reunite"], meaning: "화해시키다" },
  { word: "severe", synonyms: ["harsh", "extreme", "rigorous", "strict"], meaning: "엄한, 가혹한" },
  { word: "surge", synonyms: ["increase", "rise", "wax"], meaning: "급증하다" },
  { word: "hasten", synonyms: ["accelerate", "rush", "hurry", "speed up"], meaning: "재촉하다" },
  { word: "tentatively", synonyms: ["without certainty", "uncertainly", "hesitantly"], meaning: "머뭇거리며" },
  { word: "scorn", synonyms: ["ridicule", "disdain", "sneer", "despise"], meaning: "비웃다, 경멸하다" },
  { word: "throughout", synonyms: ["during every part of", "during the whole of"], meaning: "~동안, 내내" },
  { word: "pitfall", synonyms: ["difficulty", "trouble"], meaning: "위험, 어려움" },
  { word: "coupled with", synonyms: ["together with", "combined with"], meaning: "~과 결합된" },
  { word: "huge", synonyms: ["enormous", "massive", "large", "mammoth", "gigantic"], meaning: "거대한" },
  { word: "span", synonyms: ["duration", "period", "length", "extend across", "cover", "cross"], meaning: "기간; 걸치다" },
  { word: "hollow", synonyms: ["empty", "vacant", "void", "unfilled"], meaning: "속이 빈" },
  { word: "appreciable", synonyms: ["significant", "noticeable", "considerable"], meaning: "주목할 만한" },
  { word: "shield", synonyms: ["protect", "defend", "Safeguard"], meaning: "보호하다" },
  { word: "spearhead", synonyms: ["lead", "lead the way", "head"], meaning: "앞장서다" },
  { word: "methodically", synonyms: ["systematically"], meaning: "체계적으로" },
  { word: "manage to", synonyms: ["be able to"], meaning: "간신히~하다" },
];

const day15Words = [
  { word: "intact", synonyms: ["undamaged", "unbroken", "whole", "complete", "unaffected"], meaning: "손상되지 않은" },
  { word: "albeit", synonyms: ["although", "though", "even though"], meaning: "비록~ 이지만" },
  { word: "complex", synonyms: ["intricate", "complicated", "elaborate", "involved"], meaning: "복잡한; 복합 건물; 복합체" },
  { word: "conventional", synonyms: ["traditional", "customary", "standard", "usual"], meaning: "전통적인; 통례의" },
  { word: "reasonable", synonyms: ["sensible", "rational", "logical", "sufficient"], meaning: "합리적인; (가격이) 적당한" },
  { word: "attainment", synonyms: ["achievement", "accomplishment", "fulfillment"], meaning: "성취" },
  { word: "progressively", synonyms: ["increasingly"], meaning: "점진적으로" },
  { word: "drawback", synonyms: ["disadvantage", "problem", "defect", "shortcoming"], meaning: "결점" },
  { word: "suppress", synonyms: ["hold back", "restrain", "stop by force"], meaning: "억제하다, 참다; 진압하다" },
  { word: "incidentally", synonyms: ["by the way"], meaning: "덧붙여 말하자면, 그런데" },
  { word: "tactic", synonyms: ["strategy", "maneuver"], meaning: "전략" },
  { word: "substantial", synonyms: ["fairly large", "considerable", "significant", "noticeable"], meaning: "상당한" },
  { word: "verify", synonyms: ["confirm", "establish the truth of", "validate"], meaning: "입증하다" },
  { word: "sustained", synonyms: ["continued", "constant", "uninterrupted", "prolonged"], meaning: "지속적인" },
  { word: "radical", synonyms: ["fundamental", "basic", "extreme", "drastic"], meaning: "근본적인; 극단적인, 과격한" },
  { word: "prime", synonyms: ["peak", "high-quality", "superior", "main"], meaning: "최고의, 주요한" },
  { word: "grasp", synonyms: ["understand", "catch", "comprehend", "apprehend"], meaning: "이해하다" },
  { word: "prominently", synonyms: ["very noticeably", "conspicuously", "notably"], meaning: "눈에 띄게" },
  { word: "precipitate", synonyms: ["bring about", "cause", "give rise to", "trigger"], meaning: "재촉하다, 촉진하다" },
  { word: "interlock", synonyms: ["link", "connect", "join"], meaning: "서로 맞물리다" },
  { word: "accordingly", synonyms: ["consequently", "for that reason"], meaning: "그에 따라서" },
  { word: "relevant", synonyms: ["applicable", "pertinent", "germane"], meaning: "관련된, 적절한" },
  { word: "remarkably", synonyms: ["surprisingly"], meaning: "신기하게도" },
  { word: "disputable", synonyms: ["challengeable", "debatable", "arguable"], meaning: "논란의 여지가 있는" },
  { word: "ambitious", synonyms: ["desiring success", "aspiring"], meaning: "야심 있는" },
  { word: "congeal", synonyms: ["solidify", "harden", "stiffen", "condense"], meaning: "굳다, 응고하다" },
  { word: "cautious", synonyms: ["careful", "wary", "prudent", "discreet"], meaning: "신중한, 조심성 있는" },
  { word: "realm", synonyms: ["field", "sphere", "area", "domain"], meaning: "영역, 범위" },
  { word: "dam", synonyms: ["block", "obstruct"], meaning: "(독으로) 막다" },
  { word: "flattery", synonyms: ["praise"], meaning: "아첨" },
  { word: "amplify", synonyms: ["increase", "magnify", "enlarge", "expand"], meaning: "확대하다, 증대하다" },
  { word: "dimension", synonyms: ["size", "magnitude"], meaning: "크기, 규모" },
  { word: "deplete", synonyms: ["exhaust", "empty", "use up", "reduce"], meaning: "다 써버리다; 대폭 감소시키다" },
  { word: "characteristic", synonyms: ["distinctive", "peculiar", "special", "quality", "feature", "trait"], meaning: "특유의; 특징, 특성" },
  { word: "ice sheet", synonyms: ["glacier"], meaning: "대륙 빙하" },
  { word: "spectator", synonyms: ["viewer", "onlooker"], meaning: "관객, 구경꾼" },
  { word: "bountifully", synonyms: ["abundantly", "copiously", "plentifully", "exuberantly"], meaning: "풍부하게" },
  { word: "suffer paralysis", synonyms: ["lose the ability to move"], meaning: "마비를 겪다" },
  { word: "variation", synonyms: ["variance", "fluctuation", "difference"], meaning: "변동, 차이" },
  { word: "periphery", synonyms: ["edge", "boundary", "border", "fringe"], meaning: "주변" },
  { word: "apparently", synonyms: ["seemingly", "ostensibly", "outwardly"], meaning: "외관상으로는" },
  { word: "far-reaching", synonyms: ["extensive", "widespread", "broad"], meaning: "광범위한" },
  { word: "embody", synonyms: ["incarnate", "represent", "manifest", "contain", "incorporate"], meaning: "구체적으로 나타내다; 포함하다" },
  { word: "evade", synonyms: ["escape", "avoid", "elude", "dodge", "shun"], meaning: "피하다" },
  { word: "against", synonyms: ["next to", "beside"], meaning: "~에 붙여, ~에 가까이" },
  { word: "due to", synonyms: ["caused by", "owing to", "attributable to"], meaning: "~로 인한, ~에 기인하는" },
  { word: "classify", synonyms: ["categorize", "arrange", "assort"], meaning: "분류하다" },
  { word: "oblige", synonyms: ["force", "require", "compel"], meaning: "강요하다" },
  { word: "identical", synonyms: ["same", "indistinguishable", "equal"], meaning: "동일한" },
  { word: "intimately", synonyms: ["closely"], meaning: "친밀하게" },
  { word: "questionable", synonyms: ["doubtful", "suspicious", "dubious"], meaning: "의심스러운" },
  { word: "spot", synonyms: ["detect", "see", "find"], meaning: "발견하다" },
  { word: "immerse", synonyms: ["cover", "plunge", "dip"], meaning: "(물에) 잠그다, 담그다" },
  { word: "not in consensus with", synonyms: ["not in agreement with"], meaning: "(의견이) ~와 일치하지 않은" },
  { word: "tempted to", synonyms: ["inclined to"], meaning: "~하고 싶어지다" },
  { word: "inception", synonyms: ["beginning"], meaning: "시작, 개시" },
];

const day16Words = [
  { word: "subsequently", synonyms: ["later", "afterward"], meaning: "그 후에" },
  { word: "explicit", synonyms: ["clear", "specific", "obvious", "unambiguous", "definite"], meaning: "분명한" },
  { word: "prevailing", synonyms: ["dominant", "widespread", "current", "existing"], meaning: "(의견 등이) 지배적인" },
  { word: "rudimentary", synonyms: ["basic", "elementary", "fundamental", "primitive", "undeveloped"], meaning: "기본적인, 기초의; 미발달의" },
  { word: "allude to", synonyms: ["suggest", "refer to", "imply", "indicate"], meaning: "~을 넌지시 언급하다" },
  { word: "assertive", synonyms: ["forceful", "dogmatic"], meaning: "자기주장이 강한, 독단적인" },
  { word: "fuse", synonyms: ["melt", "dissolve", "combine", "merge"], meaning: "녹다, 녹이다; 융합하다" },
  { word: "transitory", synonyms: ["short-lived", "brief", "ephemeral", "fleeting"], meaning: "일시적인" },
  { word: "inviolable", synonyms: ["without exception", "allowing no exception", "sacred"], meaning: "(법 등이) 어길 수 없는; 신성한" },
  { word: "supersede", synonyms: ["replace", "displace", "supplant", "substitute"], meaning: "대신하다" },
  { word: "abundant", synonyms: ["plentiful", "bountiful", "ample", "numerous"], meaning: "풍부한" },
  { word: "significant", synonyms: ["considerable", "substantial", "serious", "important", "essential"], meaning: "상당한; 중요한" },
  { word: "elaboration", synonyms: ["development", "improvement"], meaning: "공들여 다듬기; 이론의 전개" },
  { word: "pristine", synonyms: ["unspoiled", "pure", "untouched"], meaning: "자연 그대로의, 오염되지 않은" },
  { word: "steadily", synonyms: ["consistently", "continuously", "constantly", "at an unvarying rate"], meaning: "끊임없이" },
  { word: "hence", synonyms: ["therefore", "consequently", "thus"], meaning: "따라서, 그러므로" },
  { word: "fabricate", synonyms: ["make", "produce", "build"], meaning: "만들어 내다" },
  { word: "meet", synonyms: ["deal with", "handle"], meaning: "(문제, 위기에) 대처하다" },
  { word: "devour", synonyms: ["eat", "consume", "gulp", "gobble"], meaning: "게걸스럽게 먹다" },
  { word: "amiss", synonyms: ["wrong", "erroneous", "faulty"], meaning: "잘못된" },
  { word: "figure out", synonyms: ["determine", "calculate", "work out"], meaning: "알아내다" },
  { word: "augment", synonyms: ["supplement"], meaning: "증가시키다" },
  { word: "trespass", synonyms: ["invade", "encroach", "infringe"], meaning: "불법 침입하다" },
  { word: "deduce", synonyms: ["conclude", "infer", "derive"], meaning: "추론하다" },
  { word: "quantify", synonyms: ["measure"], meaning: "양을 재다, 측정하다" },
  { word: "aggregation", synonyms: ["group", "body", "assemblage"], meaning: "집단" },
  { word: "lax", synonyms: ["careless", "neglectful", "negligent"], meaning: "태만한" },
  { word: "pace", synonyms: ["speed", "rate", "tempo"], meaning: "속도" },
  { word: "inspect", synonyms: ["examine", "scan", "check"], meaning: "검사하다" },
  { word: "keen", synonyms: ["sharp", "acute"], meaning: "예리한" },
  { word: "abandon", synonyms: ["desert", "give up", "forsake", "relinquish"], meaning: "버리다, 포기하다" },
  { word: "prowess", synonyms: ["ability", "competence", "expertise"], meaning: "뛰어난 솜씨" },
  { word: "anyone can see", synonyms: ["it is clear", "it is apparent"], meaning: "누가 봐도 알 수 있듯이" },
  { word: "coarse", synonyms: ["rough", "crude"], meaning: "거친" },
  { word: "impervious", synonyms: ["impermeable", "resistant", "impenetrable"], meaning: "통과 할 수 없는" },
  { word: "moderate", synonyms: ["lessen", "diminish", "gentle", "temperate", "mild"], meaning: "누그러지다; 온건한, 온화한" },
  { word: "stagnant", synonyms: ["inactive", "sluggish"], meaning: "활발하지 않은" },
  { word: "derive", synonyms: ["propel", "force", "push", "impel", "compel"], meaning: "몰아가다; 추진력, 진취성; (조직적인) 운동" },
  { word: "anxiety", synonyms: ["worry", "angst", "uneasiness"], meaning: "걱정, 불안" },
  { word: "allegedly", synonyms: ["supposedly", "reportedly"], meaning: "전해지는 바에 의하면" },
  { word: "utilize", synonyms: ["employ", "use", "make use of"], meaning: "이용하다" },
  { word: "differential", synonyms: ["uneven", "discriminatory"], meaning: "차별적인" },
  { word: "maintain", synonyms: ["preserve", "continue", "sustain", "keep", "claim", "assert", "contend"], meaning: "유지하다; 주장하다" },
  { word: "jointly", synonyms: ["together", "in conjunction with", "as one"], meaning: "함께, 공동으로" },
  { word: "catastrophic", synonyms: ["disastrous", "harmful", "tragic", "calamitous"], meaning: "비극적인, 파멸의" },
  { word: "aridity", synonyms: ["dryness", "waterlessness"], meaning: "건조함" },
  { word: "paradoxically", synonyms: ["contradictorily", "surprisingly"], meaning: "역설적으로" },
  { word: "archetypal", synonyms: ["ideal", "classic", "exemplary"], meaning: "전형적인" },
  { word: "purposely", synonyms: ["intentionally", "deliberately", "knowingly"], meaning: "고의로" },
  { word: "collision", synonyms: ["crash", "smash"], meaning: "충돌" },
  { word: "implant", synonyms: ["insert", "embed"], meaning: "심다, 끼워 넣다" },
  { word: "standpoint", synonyms: ["perspective", "point of view"], meaning: "관점, 견해" },
  { word: "cue", synonyms: ["signal", "sign"], meaning: "신호" },
  { word: "trappings", synonyms: ["decoration", "ornament", "adornment"], meaning: "장식, 장신구" },
  { word: "spawn", synonyms: ["give rise to", "create", "produce"], meaning: "야기하다" },
  { word: "outbreak", synonyms: ["sudden upsurge", "increase"], meaning: "급격한 증가, (질병 등의) 창궐" },
];

const day17Words = [
  { word: "prolonged", synonyms: ["lengthy", "extended", "protracted"], meaning: "오래 계속되는" },
  { word: "relative", synonyms: ["comparable"], meaning: "상대적인" },
  { word: "ultimate", synonyms: ["eventual", "final", "supreme", "fundamental", "basic", "primary"], meaning: "최종의, 궁극적인; 근본적인" },
  { word: "brittle", synonyms: ["easily broken", "breakable", "fragile"], meaning: "부러지기 쉬운, 깨지기 쉬운" },
  { word: "pioneer", synonyms: ["leader", "founder", "first develop", "first start", "first use", "introduce"], meaning: "선구자; 개척하다" },
  { word: "heritage", synonyms: ["inheritance", "legacy", "tradition"], meaning: "유산; 전통" },
  { word: "impetus", synonyms: ["motivation", "stimulus", "spur", "impulse"], meaning: "자극" },
  { word: "threshold", synonyms: ["limit", "margin"], meaning: "한계점, 기준점" },
  { word: "intensify", synonyms: ["reinforce", "strengthen", "enhance"], meaning: "강화하다" },
  { word: "orchestrate", synonyms: ["coordinate", "organize"], meaning: "조직하다" },
  { word: "hamper", synonyms: ["obstruct", "impede", "hinder", "restrict", "prevent"], meaning: "방해하다" },
  { word: "inhospitable", synonyms: ["unfavorable", "unfriendly", "not suitable", "uninhabitable"], meaning: "불친절한; 살기에 부적절한" },
  { word: "roughly", synonyms: ["approximately", "nearly", "about"], meaning: "대략" },
  { word: "prevalent", synonyms: ["common", "general", "widespread"], meaning: "일반적인, 널리 퍼진" },
  { word: "orientation", synonyms: ["perspective", "inclination", "disposition", "introduction", "induction"], meaning: "성향, 경향; 오리엔테이션" },
  { word: "converge", synonyms: ["come together", "meet", "move closer", "gather"], meaning: "모이다" },
  { word: "inflate", synonyms: ["swell", "bloat", "expand", "enlarge"], meaning: "부풀다, 부풀리다" },
  { word: "terrain", synonyms: ["Ground", "landscape", "topography"], meaning: "지형, 지역" },
  { word: "critically", synonyms: ["fundamentally", "decisively", "crucially"], meaning: "결정적으로" },
  { word: "in earnest", synonyms: ["seriously", "earnestly", "solemnly"], meaning: "진지하게" },
  { word: "agile", synonyms: ["nimble", "quick", "active"], meaning: "민첩한" },
  { word: "standstill", synonyms: ["complete stop", "halt"], meaning: "정지, 멈춤" },
  { word: "persuasively", synonyms: ["convincingly", "compellingly"], meaning: "설득력 있게" },
  { word: "miraculous", synonyms: ["amazing", "astonishing", "marvelous", "unbelievable"], meaning: "기적적인, 놀라운" },
  { word: "intangible", synonyms: ["nonmaterial", "impalpable", "incorporeal"], meaning: "무형의" },
  { word: "secure", synonyms: ["obtain", "get", "acquire", "procure", "safe"], meaning: "확보하다; 안전한" },
  { word: "subsist", synonyms: ["survive", "endure", "exist"], meaning: "생존하다" },
  { word: "undoubtedly", synonyms: ["certainly", "definitely", "without question"], meaning: "확실히" },
  { word: "dispose of", synonyms: ["get rid of"], meaning: "~을 처리하다" },
  { word: "archive", synonyms: ["official document", "record"], meaning: "공식 기록" },
  { word: "regenerate", synonyms: ["renew", "revive", "revitalize"], meaning: "재건하다, 재생시키다" },
  { word: "mode", synonyms: ["method", "form", "fashion", "style"], meaning: "방식, 형태" },
  { word: "commemorate", synonyms: ["celebrate", "memorialize"], meaning: "기념하다" },
  { word: "imprecise", synonyms: ["inexact", "inaccurate"], meaning: "부정확한" },
  { word: "state", synonyms: ["indicate", "specify", "express"], meaning: "명시하다" },
  { word: "anticipate", synonyms: ["expect", "foresee", "predict", "forecast"], meaning: "예상하다" },
  { word: "henceforth", synonyms: ["from now on", "hereafter"], meaning: "지금부터는" },
  { word: "transparent", synonyms: ["clear", "obvious", "lucid", "limpid"], meaning: "투명한, 명백한" },
  { word: "prominence", synonyms: ["importance", "greatness"], meaning: "중요성" },
  { word: "incorporate", synonyms: ["include", "combine", "integrate"], meaning: "통합하다" },
  { word: "meticulous", synonyms: ["careful", "thorough", "precise"], meaning: "꼼꼼한" },
  { word: "dismantle", synonyms: ["take apart", "disassemble", "break down"], meaning: "분해하다" },
  { word: "lavish", synonyms: ["rich", "deluxe", "luxurious"], meaning: "풍부한, 호화로운" },
  { word: "dynamic", synonyms: ["active", "energetic", "vigorous", "robust", "energy", "power", "driving force"], meaning: "역동적인; 원동력, 힘" },
  { word: "overlook", synonyms: ["miss", "fail to notice"], meaning: "간과하다" },
  { word: "dormant", synonyms: ["inactive", "torpid"], meaning: "활동하지 않는, 휴면 중인" },
  { word: "exempt", synonyms: ["free", "immune", "not subject to", "excused"], meaning: "면제된" },
  { word: "as a whole", synonyms: ["generally", "overall", "together", "by and large"], meaning: "전체적으로" },
  { word: "rather", synonyms: ["instead", "somewhat", "slightly"], meaning: "오히려; 좀, 약간" },
  { word: "justify", synonyms: ["support", "prove", "give a rational basis of"], meaning: "옹호하다, (정당성을) 증명하다" },
  { word: "chaotic", synonyms: ["disorganized", "disordered", "anarchic"], meaning: "무질서한" },
  { word: "commence", synonyms: ["begin", "start", "originate", "initiate"], meaning: "시작하다" },
  { word: "improvised", synonyms: ["unplanned", "unprepared", "unrehearsed"], meaning: "즉흥의" },
  { word: "stem from", synonyms: ["originate from", "derive from", "arise from"], meaning: "~에서 유래하다" },
  { word: "judiciously", synonyms: ["wisely", "sensibly", "prudently"], meaning: "현명하게, 분별 있게" },
  { word: "tolerate", synonyms: ["accept", "allow", "permit"], meaning: "용인하다, 허용하다" },
];

const day18Words = [
  { word: "initiative", synonyms: ["enterprise", "ambition", "drive"], meaning: "진취성" },
  { word: "provided that", synonyms: ["if", "once", "on condition that", "supposing"], meaning: "만약~이라면" },
  { word: "phenomenal", synonyms: ["extraordinary", "remarkable"], meaning: "경이적인" },
  { word: "likewise", synonyms: ["similarly", "in the same way", "also", "as well"], meaning: "마찬가지로, 똑같이; 또한" },
  { word: "tangible", synonyms: ["material", "physical", "concrete", "substantial"], meaning: "유형의, 실재하는" },
  { word: "absurd", synonyms: ["ridiculous", "preposterous", "ludicrous"], meaning: "터무니없는" },
  { word: "inclement", synonyms: ["unfavorable", "harsh", "severe"], meaning: "(날씨가) 혹독한" },
  { word: "overly", synonyms: ["excessively", "inordinately", "unduly"], meaning: "지나치게" },
  { word: "consume", synonyms: ["expend", "use up", "completely use", "exhaust", "destroy", "devastate", "demolish"], meaning: "소모하다, 다 써버리다; 소멸하다" },
  { word: "overall", synonyms: ["general", "total", "comprehensive"], meaning: "전반적인" },
  { word: "promote", synonyms: ["encourage", "advance", "further", "forward"], meaning: "촉진하다" },
  { word: "proliferation", synonyms: ["increase", "multiplication", "growth"], meaning: "급증" },
  { word: "copious", synonyms: ["plentiful", "abundant", "ample", "bountiful"], meaning: "풍부한" },
  { word: "negligible", synonyms: ["insignificant", "slight", "minor", "trivial"], meaning: "사소한" },
  { word: "notably", synonyms: ["particularly", "especially", "in particular"], meaning: "특히" },
  { word: "inhibit", synonyms: ["hinder", "restrict", "restrain", "ban", "limit", "prohibit", "forbid"], meaning: "금지하다" },
  { word: "worshiper", synonyms: ["people participating in a religious service"], meaning: "예배자" },
  { word: "pool", synonyms: ["combine", "put together", "combination", "group"], meaning: "모으다; 기업, 연합" },
  { word: "at the urging of", synonyms: ["at the recommendation of"], meaning: "~의 권고로" },
  { word: "ornamental", synonyms: ["decorative", "beautifying", "embellishing"], meaning: "장식용의" },
  { word: "regime", synonyms: ["government", "administration", "authorities"], meaning: "정권, 체계" },
  { word: "acclaim", synonyms: ["praise", "compliment", "applaud"], meaning: "격찬하다" },
  { word: "comprehensible", synonyms: ["understandable", "apprehensible", "knowable"], meaning: "이해할 수 있는" },
  { word: "disparity", synonyms: ["inequality", "imbalance", "disproportion"], meaning: "차이, 불균형" },
  { word: "bold", synonyms: ["daring", "brace", "courageous"], meaning: "용감한" },
  { word: "noteworthy", synonyms: ["important", "notable", "significant"], meaning: "주목할 만한" },
  { word: "spectacular", synonyms: ["magnificent", "splendid", "impressive"], meaning: "장관인, 눈부신" },
  { word: "extracted from", synonyms: ["taken out of", "drawn out of"], meaning: "~에서 뽑아낸" },
  { word: "tantalize", synonyms: ["tempt"], meaning: "애타게 하다" },
  { word: "allied", synonyms: ["related", "linked", "connected"], meaning: "관련된" },
  { word: "authoritative", synonyms: ["official", "authorized"], meaning: "권위 있는, 믿을 만한" },
  { word: "moral", synonyms: ["lesson", "message", "teaching"], meaning: "교훈" },
  { word: "compatible", synonyms: ["consistent", "congruous", "consonant"], meaning: "일치하는, 양립할 수 있는" },
  { word: "buildup", synonyms: ["accumulation"], meaning: "축적" },
  { word: "stress", synonyms: ["emphasize", "highlight", "underline", "emphasis", "accent"], meaning: "강조하다; 중점, 강조" },
  { word: "respective", synonyms: ["particular", "individual"], meaning: "각각의, 개별적인" },
  { word: "peculiarity", synonyms: ["feature", "characteristic", "quality"], meaning: "(기이한) 특징, 특성" },
  { word: "rely upon", synonyms: ["depend upon", "resort to"], meaning: "~에 의존하다" },
  { word: "rapid", synonyms: ["fast", "quick", "speedy", "swift"], meaning: "빠른" },
  { word: "saturate", synonyms: ["soak", "drench", "wet thoroughly"], meaning: "흠뻑 적시다" },
  { word: "constitution", synonyms: ["form", "structure"], meaning: "구성, 구조" },
  { word: "efface", synonyms: ["wipe out", "erase", "expunge"], meaning: "지우다, 없애다" },
  { word: "manageable", synonyms: ["controllable", "affordable", "easy to handle"], meaning: "관리하기 쉬운" },
  { word: "approach", synonyms: ["come close", "move toward", "come toward", "near", "reach", "method", "way"], meaning: "접근하다; 접근법" },
  { word: "routinely", synonyms: ["regularly", "commonly", "habitually"], meaning: "일상적으로" },
  { word: "adapt", synonyms: ["adjust", "acclimate", "conform"], meaning: "적응하다" },
  { word: "implication", synonyms: ["consequence", "result"], meaning: "결과" },
  { word: "unambiguous", synonyms: ["clear", "distinct", "definite"], meaning: "분명한" },
  { word: "rigor", synonyms: ["harshness", "strictness", "rigidness", "hardship", "adversity"], meaning: "엄격한; 고초, 어려움" },
  { word: "contentious", synonyms: ["disputed", "controversial", "argumentative"], meaning: "논쟁을 불러일으키는" },
  { word: "competent", synonyms: ["adept", "skilled", "capable"], meaning: "유능한" },
  { word: "incredible", synonyms: ["unbelievable", "inconceivable", "unimaginable"], meaning: "믿기 힘든" },
  { word: "string", synonyms: ["series", "chain"], meaning: "일련" },
  { word: "decompose", synonyms: ["decay", "rot"], meaning: "부패하다" },
  { word: "lateral", synonyms: ["side"], meaning: "측면의" },
];

const day19Words = [
  { word: "forage", synonyms: ["seek for food", "search", "hunt", "rummage", "feed", "fodder", "food"], meaning: "(식량 등을) 찾아다니다; 사료, 먹이" },
  { word: "erect", synonyms: ["build", "construct", "raise", "set up"], meaning: "세우다, 건설하다" },
  { word: "integral", synonyms: ["essential", "crucial", "indispensable", "complete"], meaning: "필수적인; 완전한, 빠진 것이 없는" },
  { word: "precisely", synonyms: ["exactly", "accurately", "correctly", "with precision"], meaning: "정확하게" },
  { word: "handle", synonyms: ["process", "manage", "deal with"], meaning: "처리하다" },
  { word: "objective", synonyms: ["purpose", "aim", "goal", "unbiased", "impartial"], meaning: "목적, 목표; 편견 없는" },
  { word: "vigor", synonyms: ["energy", "strength", "vitality"], meaning: "활력, 힘" },
  { word: "deviate", synonyms: ["turn", "depart", "aside", "diverge", "stray"], meaning: "벗어나다" },
  { word: "decisive", synonyms: ["significant", "definitive", "definite"], meaning: "결정적인, 명백한" },
  { word: "primordial", synonyms: ["beginning", "original", "earliest"], meaning: "최초의" },
  { word: "cluster", synonyms: ["gather", "group", "assemble"], meaning: "(떼를 지어) 모이다, 모으다" },
  { word: "revise", synonyms: ["change", "modify", "alter", "edit", "correct"], meaning: "수정하다, 변경하다" },
  { word: "obscure", synonyms: ["unclear", "uncertain", "hidden", "dim", "faint"], meaning: "흐릿한, 불분명한" },
  { word: "rebound", synonyms: ["recover", "rally", "bounce back", "recovery", "return"], meaning: "회복" },
  { word: "thus", synonyms: ["consequently", "therefore", "accordingly"], meaning: "따라서" },
  { word: "minutely", synonyms: ["in detail", "meticulously"], meaning: "자세하게" },
  { word: "tend", synonyms: ["take care of", "look after", "care for", "foster"], meaning: "돌보다" },
  { word: "impact", synonyms: ["influence", "effect", "repercussion"], meaning: "영향" },
  { word: "luxuriant", synonyms: ["rich", "abundant", "exuberant", "opulent"], meaning: "무성한" },
  { word: "altogether", synonyms: ["fully", "completely", "entirely", "totally", "wholly"], meaning: "완전히" },
  { word: "astounding", synonyms: ["amazing", "astonishing", "surprising"], meaning: "놀라운" },
  { word: "propagation", synonyms: ["spread", "dissemination"], meaning: "보급, 전파" },
  { word: "encroach", synonyms: ["trespass", "invade", "intrude"], meaning: "침입하다" },
  { word: "bizarre", synonyms: ["strange", "odd", "erratic", "exotic", "irregular"], meaning: "이상한, 기괴한" },
  { word: "elevate", synonyms: ["raise", "lift", "heave", "hoist"], meaning: "들어 올리다" },
  { word: "superb", synonyms: ["excellent", "outstanding", "magnificent"], meaning: "훌륭한" },
  { word: "accommodate", synonyms: ["lodge", "make room for", "hold", "adjust to", "suit", "adapt", "fit"], meaning: "수용하다; 적응하다, 맞추다" },
  { word: "infinite", synonyms: ["limitless", "unlimited", "immeasurable", "boundless"], meaning: "무한한" },
  { word: "glimpse into", synonyms: ["brief view into", "quick look into"], meaning: "~을 흘끗 봄" },
  { word: "mold", synonyms: ["shape", "form", "fashion"], meaning: "형성하다, 만들다" },
  { word: "wary", synonyms: ["cautious", "distrustful", "watchful"], meaning: "경계하는" },
  { word: "expansion", synonyms: ["spread", "growth"], meaning: "팽창, 확장" },
  { word: "autonomy", synonyms: ["self-rule", "independence"], meaning: "자치(권)" },
  { word: "complaint", synonyms: ["protest", "grievance"], meaning: "불안, 항의" },
  { word: "subordinate", synonyms: ["secondary", "subject"], meaning: "종속적인" },
  { word: "thrive", synonyms: ["do well", "prosper", "flourish"], meaning: "번성하다" },
  { word: "by and large", synonyms: ["for the most part", "on the whole", "generally"], meaning: "대체로" },
  { word: "unique to", synonyms: ["existing only in", "exclusive to"], meaning: "~ 특유의" },
  { word: "annual", synonyms: ["yearly"], meaning: "연간의" },
  { word: "frigid", synonyms: ["cold", "freezing", "frosty"], meaning: "몹시 추운" },
  { word: "appreciate", synonyms: ["recognize", "understand", "perceive"], meaning: "인식하다" },
  { word: "apparatus", synonyms: ["equipment", "device"], meaning: "기구, 장치" },
  { word: "engender", synonyms: ["cause", "bring about", "generate"], meaning: "야기하다" },
  { word: "adverse", synonyms: ["unfavorable", "negative", "not favorable", "harmful"], meaning: "부정적인" },
  { word: "accomplished", synonyms: ["skilled", "proficient"], meaning: "숙련된" },
  { word: "conceal", synonyms: ["hid", "cover", "obscure"], meaning: "숨기다, 감추다" },
  { word: "uniform", synonyms: ["consistent", "even", "invariable"], meaning: "일정한, 한결같은" },
  { word: "complement", synonyms: ["supplement"], meaning: "금상천화적 요소, 보완물" },
  { word: "refrain from", synonyms: ["avoid", "abstain from", "keep from"], meaning: "~을 피하다" },
  { word: "column", synonyms: ["pillar", "post"], meaning: "기둥" },
  { word: "underscore", synonyms: ["emphasize", "reinforce", "underline", "accentuate"], meaning: "강조하다" },
  { word: "inspire", synonyms: ["motivate", "fire the imagination of"], meaning: "영감을 주다" },
  { word: "swell", synonyms: ["increase", "expand", "enlarge"], meaning: "팽창하다, 팽창시키다" },
  { word: "deficient", synonyms: ["not enough", "insufficient", "inadequate"], meaning: "부족한" },
  { word: "indiscriminately", synonyms: ["randomly"], meaning: "무차별로, 가리지 않고" },
  { word: "to some extent", synonyms: ["within limits"], meaning: "어느 정도까지" },
  { word: "hierarchical", synonyms: ["arranged in order of"], meaning: "계급제의" },
];

const day20Words = [
  { word: "harness", synonyms: ["utilize", "put to use", "employ"], meaning: "(자연의 힘 등을) 이용하다" },
  { word: "prestige", synonyms: ["high regard", "status"], meaning: "명성, 위산" },
  { word: "radically", synonyms: ["extremely", "completely", "essentially"], meaning: "철저하게; 근본적으로" },
  { word: "exhibit", synonyms: ["show", "display", "present", "demonstrate", "set forth"], meaning: "보이다, 나타내다" },
  { word: "deposit", synonyms: ["lay", "place", "lay down", "set down", "leave behind"], meaning: "놓다, 두다" },
  { word: "shatter", synonyms: ["break", "destroy", "smash"], meaning: "산산이 부수다" },
  { word: "barren", synonyms: ["infertile", "sterile", "lifeless", "unable to sustain life"], meaning: "척박한, 불모의" },
  { word: "consent", synonyms: ["agree", "assent"], meaning: "동의하다" },
  { word: "give rise to", synonyms: ["cause", "produce", "provoke", "bring about"], meaning: "~을 초래하다" },
  { word: "size up", synonyms: ["evaluate", "measure", "assess", "appraise"], meaning: "평가하다" },
  { word: "mimic", synonyms: ["imitate", "copy", "reproduce"], meaning: "흉내 내다, 모방하다" },
  { word: "contiguous", synonyms: ["neighboring", "adjacent", "adjoining"], meaning: "인접한" },
  { word: "engage", synonyms: ["involve", "reserve", "book", "hire"], meaning: "참여시키다, (대화 등에) 끌어들이다; (방, 좌석 등을) 예약하다; 고용하다" },
  { word: "initial", synonyms: ["first", "original", "earliest"], meaning: "최초의" },
  { word: "essential", synonyms: ["fundamental", "indispensable", "required"], meaning: "근본적인; 필수적인" },
  { word: "relevant", synonyms: ["related", "pertinent", "germane"], meaning: "관련된" },
  { word: "traumatic", synonyms: ["highly stressful", "upsetting", "disturbing"], meaning: "정신적 충격이 큰" },
  { word: "on the whole", synonyms: ["in general", "generally", "overall", "by and large"], meaning: "대체로" },
  { word: "dispersal", synonyms: ["distribution", "scattering"], meaning: "확산, 분산" },
  { word: "sought-after", synonyms: ["desired", "desirable", "in demand"], meaning: "수요가 많은, 인기 있는" },
  { word: "expand", synonyms: ["enlarge", "increase", "swell", "bloat"], meaning: "확장시키다, 확장하다" },
  { word: "mastery", synonyms: ["control", "expertise"], meaning: "통제력, 지배; 전문적 지식" },
  { word: "perpetually", synonyms: ["continually", "incessantly", "ceaselessly"], meaning: "끊임없이" },
  { word: "evacuate", synonyms: ["move out"], meaning: "대피하다, 비우고 떠나다" },
  { word: "excrete", synonyms: ["expel", "discharge", "eject"], meaning: "배설하다, 방출하다" },
  { word: "gradually", synonyms: ["slowly", "little by little"], meaning: "서서히" },
  { word: "affluent", synonyms: ["plentiful", "abundant", "wealthy", "rich", "well-off"], meaning: "풍부한; 부유한" },
  { word: "stationary", synonyms: ["unmoving", "motionless", "immobile"], meaning: "움직이지 않는" },
  { word: "cling to", synonyms: ["stick to", "hold tightly", "adhere to"], meaning: "~에 달라붙다" },
  { word: "endow", synonyms: ["donate", "grant", "provide", "endue"], meaning: "기부하다; (능력, 재능 등을) 부여하다" },
  { word: "verging on", synonyms: ["bordering on"], meaning: "~에 가까운, 거의~인" },
  { word: "contemptuous", synonyms: ["scornful", "disdainful"], meaning: "업신여기는" },
  { word: "accelerate", synonyms: ["increase in speed", "speed up"], meaning: "속도를 높이다" },
  { word: "confirm", synonyms: ["ascertain", "verify"], meaning: "확인하다" },
  { word: "harsh", synonyms: ["severe", "rigorous", "inclement"], meaning: "가혹한" },
  { word: "mere subsistence", synonyms: ["basic living necessaries"], meaning: "최저 생계 수단, 생필품" },
  { word: "adherent", synonyms: ["supporter", "advocate"], meaning: "지지자" },
  { word: "invaluable", synonyms: ["precious", "priceless", "valuable"], meaning: "매우 귀중한" },
  { word: "successive", synonyms: ["sequential", "consecutive", "serial"], meaning: "연속적인" },
  { word: "coating", synonyms: ["layer", "film"], meaning: "코팅, 칠, 입힌 것" },
  { word: "resume", synonyms: ["restart", "begin again", "recommence"], meaning: "다시 시작하다" },
  { word: "dual", synonyms: ["double", "twofold"], meaning: "이중의" },
  { word: "composite", synonyms: ["mixture", "compound"], meaning: "합성물" },
  { word: "illuminate", synonyms: ["light", "brighten", "clarify"], meaning: "밝게 하다; 명확하게 하다" },
  { word: "allure", synonyms: ["attract", "invite", "appeal", "lure"], meaning: "매혹하다" },
  { word: "rekindle", synonyms: ["renew", "arouse", "reawaken"], meaning: "다시 불붙이다; 되살아나게 하다" },
  { word: "devastation", synonyms: ["destruction", "demolition", "ruin"], meaning: "파괴" },
  { word: "tentative", synonyms: ["uncertain", "unsure"], meaning: "망설이는, 불확실한" },
  { word: "suppose", synonyms: ["assume", "presume", "surmise"], meaning: "추측하다" },
  { word: "primitive", synonyms: ["early", "primeval", "simple", "rudimentary"], meaning: "원시적인; 초기의" },
  { word: "interrupt", synonyms: ["break off"], meaning: "중단시키다" },
  { word: "conform", synonyms: ["comply", "obey", "follow"], meaning: "따르다" },
  { word: "combine", synonyms: ["incorporate", "mix", "unite"], meaning: "결합시키다" },
  { word: "terminal", synonyms: ["final", "last"], meaning: "마지막의" },
  { word: "point out", synonyms: ["state", "indicate", "show"], meaning: "지적하다, 언급하다" },
];
