const day21Words = [
  { word: "flourish", synonyms: ["thrive", "prosper", "blossom", "do well"], meaning: "번창하다" },
  { word: "dissipate", synonyms: ["disperse", "scatter"], meaning: "흩뜨리다, 흩어지다" },
  { word: "profound", synonyms: ["great", "significant", "deep", "fundamental", "far-reaching"], meaning: "엄청난/심오한/폭넓은" },
  { word: "intriguing", synonyms: ["interesting but not completely understood", "fascinating"], meaning: "매우 흥미로운" },
  { word: "considerably", synonyms: ["significantly", "appreciably", "fairly"], meaning: "상당히" },
  { word: "ingenuity", synonyms: ["creativeness", "inventiveness", "cleverness"], meaning: "창의력, 교묘한" },
  { word: "conquer", synonyms: ["defeat", "prevail", "triumph"], meaning: "이기다" },
  { word: "fragment", synonyms: ["piece", "flake", "particle", "part", "break apart", "shatter", "divide"], meaning: "조각, 부분/산산이 부수다" },
  { word: "spell", synonyms: ["a certain period of time"], meaning: "한동안" },
  { word: "facet", synonyms: ["aspect", "phase"], meaning: "측면" },
  { word: "mundane", synonyms: ["ordinary", "banal", "commonplace"], meaning: "일상적인" },
  { word: "dense", synonyms: ["crowded", "thick", "compact"], meaning: "밀집한" },
  { word: "random", synonyms: ["unplanned", "unpredictable", "chance"], meaning: "무작위의, 우연한" },
  { word: "mere", synonyms: ["nothing more than", "insignificant"], meaning: "하찮은" },
  { word: "persistence", synonyms: ["continuation", "ceaselessness"], meaning: "지속" },
  { word: "intrusive", synonyms: ["interfering", "meddlesome"], meaning: "개입하는" },
  { word: "culminate in", synonyms: ["reach completion in", "reach the highest point in"], meaning: "~절정에 달하다" },
  { word: "stabilize", synonyms: ["hold in place", "support"], meaning: "안정시키다" },
  { word: "prompt", synonyms: ["cause", "bring about", "induce", "stimulate"], meaning: "유발하다" },
  { word: "distinction", synonyms: ["difference", "divergence", "contrast"], meaning: "차이" },
  { word: "constant", synonyms: ["unchangeable", "steady", "stationary"], meaning: "변함없는" },
  { word: "appreciation", synonyms: ["understanding", "comprehension"], meaning: "이해" },
  { word: "sophistication", synonyms: ["Expertise"], meaning: "지식" },
  { word: "pronouncement", synonyms: ["statement", "declaration", "proclamation"], meaning: "선언" },
  { word: "flag", synonyms: ["lessen", "weaken", "fade", "wither"], meaning: "시들다" },
  { word: "ambivalent", synonyms: ["mixed", "unsure", "undecided"], meaning: "상반된 감정이 있는" },
  { word: "term", synonyms: ["call", "name", "designate", "denominate"], meaning: "칭하다" },
  { word: "flawed", synonyms: ["incorrect", "defective", "imperfect"], meaning: "결함이 있는" },
  { word: "reminisce", synonyms: ["recollect", "remember", "recall", "look back"], meaning: "회상하다" },
  { word: "destitute of", synonyms: ["lacking", "empty of", "deficient in"], meaning: "~이 없는" },
  { word: "regrettably", synonyms: ["unfortunately", "lamentably", "sadly"], meaning: "유감스럽게도" },
  { word: "principle", synonyms: ["basic method", "original method"], meaning: "원리" },
  { word: "contain", synonyms: ["include", "comprise"], meaning: "포함하다" },
  { word: "juncture", synonyms: ["connection", "junction", "link"], meaning: "연결" },
  { word: "discount", synonyms: ["ignore", "disregard"], meaning: "무시하다" },
  { word: "or so", synonyms: ["Roughly"], meaning: "~정도" },
  { word: "dejected", synonyms: ["depressed", "downhearted"], meaning: "낙담한" },
  { word: "proposal", synonyms: ["idea", "offer", "proposition", "suggestion"], meaning: "제안" },
  { word: "for all", synonyms: ["in spite of", "with all", "despite"], meaning: "~에도 불구하고" },
  { word: "uniquely", synonyms: ["exceptionally", "distinctively"], meaning: "독특하게" },
  { word: "criticize", synonyms: ["find fault with", "blame", "condemn", "censure"], meaning: "비난하다" },
  { word: "erode", synonyms: ["wear down", "wear away", "wear out"], meaning: "침식시키다" },
  { word: "tension", synonyms: ["strain", "pressure"], meaning: "긴장" },
  { word: "ancient", synonyms: ["early", "old", "prehistoric", "antique"], meaning: "고대의" },
  { word: "inherently", synonyms: ["essentially", "intrinsically"], meaning: "본질적으로" },
  { word: "sporadic", synonyms: ["occasional", "intermittent", "irregular", "infrequent"], meaning: "때때로 일어나는" },
  { word: "apex", synonyms: ["crest", "peak", "acme", "pinnacle"], meaning: "정점" },
  { word: "though", synonyms: ["however", "nevertheless", "yet still", "although", "while", "albeit"], meaning: "그렇지만/~이지만" },
  { word: "infer", synonyms: ["conclude", "derive", "reason", "deduce"], meaning: "추론하다" },
  { word: "core", synonyms: ["central idea", "center", "heart"], meaning: "핵심" },
  { word: "mutation", synonyms: ["change", "variation", "alternation"], meaning: "돌연변이, 변화" },
  { word: "thrill", synonyms: ["excitement", "exhilaration", "frisson"], meaning: "전율" },
  { word: "mutilate", synonyms: ["damage", "injure", "disable"], meaning: "못쓰게 만들다" },
  { word: "rigidly", synonyms: ["strictly", "rigorously", "severely"], meaning: "엄격하게" },
  { word: "matter", synonyms: ["substance", "material", "stuff", "issue"], meaning: "물질/사안" },
  { word: "contradicting", synonyms: ["Opposing"], meaning: "서로 대립하는" },
  { word: "unwilling", synonyms: ["Reluctant"], meaning: "꺼리는" },
];

const day22Words = [
  { word: "skeptical", synonyms: ["doubting", "incredulous", "dubious", "suspicious"], meaning: "의심많은" },
  { word: "optimal", synonyms: ["best", "ideal", "most satisfactory"], meaning: "최적의" },
  { word: "hint", synonyms: ["indication", "implication", "clue"], meaning: "암시" },
  { word: "challenge", synonyms: ["difficulty", "problem", "question", "dispute"], meaning: "문제/이의를 제기하다" },
  { word: "potentially", synonyms: ["possibly", "perhaps", "maybe"], meaning: "어쩌면" },
  { word: "compel", synonyms: ["force", "oblige", "require", "coerce"], meaning: "강요하다" },
  { word: "simultaneously", synonyms: ["at the same time", "concurrently", "in parallel"], meaning: "동시에" },
  { word: "static", synonyms: ["unchanging", "immobile", "unmoving"], meaning: "변화가 없는" },
  { word: "retain", synonyms: ["preserve", "keep", "maintain"], meaning: "보유하다" },
  { word: "strictly", synonyms: ["rigorously", "severely", "tightly", "precisely", "only", "exclusively", "solely"], meaning: "엄격히/오로지" },
  { word: "exceptionally", synonyms: ["uncommonly", "unusually", "distinctively"], meaning: "유난히" },
  { word: "consequently", synonyms: ["as a result", "therefore", "hence", "thus"], meaning: "그 결과, 따라서" },
  { word: "obtain", synonyms: ["acquire", "gain", "earn", "derive", "achieve"], meaning: "얻다" },
  { word: "epitomize", synonyms: ["exemplify", "typify", "represent", "summarize", "abridge"], meaning: "~의 전형이 되다/요약하다" },
  { word: "aggregate", synonyms: ["overall", "total", "combined", "collective", "gather", "collect", "combine", "accumulate", "amass"], meaning: "총계의, 집합적인/모이다" },
  { word: "in principle", synonyms: ["theoretically", "in theory", "on paper"], meaning: "이론상으로" },
  { word: "sequentially", synonyms: ["consecutively", "successively"], meaning: "연속적으로" },
  { word: "surveillance", synonyms: ["observation", "watch", "supervision"], meaning: "감시" },
  { word: "accompany", synonyms: ["occur with", "come with"], meaning: "동반하다" },
  { word: "hazardous", synonyms: ["dangerous", "perilous", "risky", "unsafe"], meaning: "위험한" },
  { word: "thwart", synonyms: ["Frustrate"], meaning: "좌절시키다" },
  { word: "vanish", synonyms: ["disappear", "fade", "evaporate"], meaning: "사라지다" },
  { word: "synthesis", synonyms: ["combination", "union", "integration"], meaning: "통합" },
  { word: "forum", synonyms: ["public area", "public square"], meaning: "공공 광장" },
  { word: "invade", synonyms: ["trespass", "enter", "intrude", "raid"], meaning: "침입하다" },
  { word: "quarters", synonyms: ["residence", "dwelling", "habitation", "abode"], meaning: "주거" },
  { word: "abolish", synonyms: ["eliminate", "end", "annul", "revoke", "nullify"], meaning: "폐지하다" },
  { word: "staggering", synonyms: ["shocking", "astonishing", "stunning", "astounding"], meaning: "충격적인" },
  { word: "disclose", synonyms: ["reveal", "divulge", "unveil"], meaning: "폭로하다" },
  { word: "scores", synonyms: ["a large number", "host", "crowd", "multitude"], meaning: "다수" },
  { word: "eager to", synonyms: ["anxious to", "keen to", "impatient to"], meaning: "~을 하고 싶어하는" },
  { word: "systematically", synonyms: ["methodically"], meaning: "체계적으로" },
  { word: "Stimulate", synonyms: ["prompt", "spur", "promote", "activate"], meaning: "자극하다" },
  { word: "Limited", synonyms: ["restricted", "narrow", "confined"], meaning: "제한된" },
  { word: "Excessive", synonyms: ["extreme", "undue", "exorbitant"], meaning: "지나친" },
  { word: "Similar", synonyms: ["comparable", "alike", "analogous"], meaning: "비슷한" },
  { word: "entitled to", synonyms: ["given the right to", "authorized to", "qualified to"], meaning: "~할 권리가 있는" },
  { word: "constantly", synonyms: ["continually", "continuously", "perpetually", "always"], meaning: "끊임없이" },
  { word: "turbulence", synonyms: ["agitation", "tumult", "commotion", "turmoil"], meaning: "소란, 동요" },
  { word: "Essence", synonyms: ["fundamental", "essentially", "substance", "nature"], meaning: "본질" },
  { word: "back up", synonyms: ["support", "stand by", "aid", "assist"], meaning: "지지하다" },
  { word: "Flexibility", synonyms: ["adaptability", "adjustability", "versatility"], meaning: "융통성" },
  { word: "Archaic", synonyms: ["antiquated", "outdated", "old", "primitive"], meaning: "구식의" },
  { word: "Eject", synonyms: ["force out", "throw out", "expel"], meaning: "쫓아내다" },
  { word: "Interpret", synonyms: ["construe", "explain", "understand"], meaning: "해석하다" },
  { word: "Intensity", synonyms: ["strength"], meaning: "강도, 세기" },
  { word: "Sloping", synonyms: ["inclining", "inclined", "slanted"], meaning: "경사진" },
  { word: "Endeavor", synonyms: ["make an effort", "strive", "struggle", "attempt"], meaning: "노력하다" },
  { word: "circumvent", synonyms: ["get around", "bypass", "detour"], meaning: "우회하다" },
  { word: "counterproductive", synonyms: ["contrary to what is necessary"], meaning: "역효과를 낳는" },
  { word: "lucid", synonyms: ["clear", "obvious", "distinct"], meaning: "명료한" },
  { word: "delineate", synonyms: ["outline", "trace"], meaning: "(윤곽을) 그리다" },
  { word: "practical", synonyms: ["pragmatic", "functional", "effective"], meaning: "실용적인" },
  { word: "revere", synonyms: ["honor", "admire", "venerate", "respect"], meaning: "존경하다" },
  { word: "unpromising", synonyms: ["unfavorable"], meaning: "가망이 없는" },
  { word: "heed", synonyms: ["attention", "notice", "caution"], meaning: "주의" },
  { word: "location", synonyms: ["region", "site", "position", "place"], meaning: "장소" },
  { word: "opposing", synonyms: ["conflicting"], meaning: "상반되는, 모순되는" },
];

const day23Words = [
  { word: "configuration", synonyms: ["arrangement", "shape", "form", "conformation"], meaning: "배치, 형태" },
  { word: "induce", synonyms: ["bring about", "cause", "stimulate", "persuade", "convince"], meaning: "유발하다/설득하다" },
  { word: "attain", synonyms: ["reach", "arrive at", "achieve", "accomplish", "realize"], meaning: "도달하다/성취하다" },
  { word: "erratic", synonyms: ["irregular", "unpredictable", "uneven"], meaning: "불규칙한" },
  { word: "eventual", synonyms: ["ultimate", "final"], meaning: "최종적인" },
  { word: "mandate", synonyms: ["order", "command", "instruction"], meaning: "명령" },
  { word: "prosperous", synonyms: ["flourishing", "thriving", "blooming", "financially successful", "wealthy", "affluent"], meaning: "번영하는/부유한" },
  { word: "requisite", synonyms: ["necessity", "requirement", "essential", "required", "necessary"], meaning: "필수조건/필수의" },
  { word: "partake of", synonyms: ["consume", "share"], meaning: "함께하다" },
  { word: "pledge", synonyms: ["promise", "oath", "vow", "undertaking"], meaning: "약속" },
  { word: "contend", synonyms: ["argue", "assert", "maintain"], meaning: "주장하다" },
  { word: "confine", synonyms: ["boundary", "limit", "cramp", "enclose", "cage", "limit"], meaning: "경계/가두다, 제한하다" },
  { word: "dictate", synonyms: ["require", "suggest", "prescribe", "determine"], meaning: "지시하다/결정하다" },
  { word: "durable", synonyms: ["long-lasting", "lasting", "enduring"], meaning: "오래가는" },
  { word: "collectively", synonyms: ["together", "all together", "unitedly"], meaning: "공동으로" },
  { word: "furnish", synonyms: ["provide", "supply", "offer"], meaning: "제공하다" },
  { word: "alter", synonyms: ["change", "modify", "metamorphose"], meaning: "변경하다" },
  { word: "determine", synonyms: ["decide", "resolve", "conclude", "figure out", "calculate"], meaning: "결정하다/측정하다" },
  { word: "haul", synonyms: ["draw", "pull", "drag", "heave"], meaning: "끌다" },
  { word: "approximation", synonyms: ["nearness", "closeness", "proximity"], meaning: "근접성" },
  { word: "found wanting", synonyms: ["judged inadequate"], meaning: "부족하다고 여겨지는" },
  { word: "classic", synonyms: ["typical", "exemplary", "model"], meaning: "전형적인" },
  { word: "grossly", synonyms: ["Excessively"], meaning: "지나치게" },
  { word: "vivid", synonyms: ["bright", "brilliant", "graphic", "lifelike"], meaning: "선명한/생생한" },
  { word: "artificial", synonyms: ["synthetic", "man-made"], meaning: "인공의" },
  { word: "transplant", synonyms: ["place in another context", "remove", "relocate"], meaning: "이동시키다" },
  { word: "camouflage", synonyms: ["hide", "disguise", "conceal"], meaning: "위장하다, 감추다" },
  { word: "implement", synonyms: ["tool", "instrument", "appliance"], meaning: "도구" },
  { word: "excavate", synonyms: ["dig out", "dig up", "unearth", "disinter"], meaning: "파내다" },
  { word: "disgust", synonyms: ["distaste", "nausea", "aversion"], meaning: "혐오감" },
  { word: "secluded", synonyms: ["remote", "hidden", "isolated", "solitary"], meaning: "외딴" },
  { word: "engulf", synonyms: ["Swallow"], meaning: "삼켜버리다" },
  { word: "chronic", synonyms: ["persistent", "constant", "incessant"], meaning: "만성적인" },
  { word: "magnificent", synonyms: ["superb", "gorgeous", "beautiful", "splendid"], meaning: "굉장히 멋진" },
  { word: "truism", synonyms: ["self-evident truth", "commonplace", "cliché"], meaning: "뻔한 말, 자명한 이치" },
  { word: "accidental", synonyms: ["unintentional", "inadvertent", "unintended"], meaning: "우연한" },
  { word: "invent", synonyms: ["devise", "originate"], meaning: "발명하다" },
  { word: "inherent in", synonyms: ["characteristic of"], meaning: "~에 내재된" },
  { word: "expose", synonyms: ["make visible", "exhibit", "uncover subject"], meaning: "노출시키다" },
  { word: "perpetuate", synonyms: ["continue", "immortalize", "eternize"], meaning: "영속시키다" },
  { word: "be inclined to", synonyms: ["tend to"], meaning: "하는 경향이 있다" },
  { word: "illusory", synonyms: ["misleading", "deceptive", "delusive"], meaning: "착각을 일으키는" },
  { word: "heyday", synonyms: ["high point", "golden age", "prime", "florescence"], meaning: "전성기" },
  { word: "proficient", synonyms: ["skilled", "skillful", "expert", "adept"], meaning: "능숙한" },
  { word: "amply", synonyms: ["generously", "bountiful", "lavishly"], meaning: "풍부하게" },
  { word: "desolate", synonyms: ["deserted", "bleak", "dreary"], meaning: "황량한" },
  { word: "more subtle", synonyms: ["less noticeable"], meaning: "더 포착하기 어려운" },
  { word: "disrupt", synonyms: ["interfere with", "interrupt", "upset"], meaning: "방해하다" },
  { word: "forerunner", synonyms: ["predecessor", "antecedent"], meaning: "선구자" },
  { word: "immediate", synonyms: ["instant", "prompt", "on-the-spot", "nearest", "neighboring", "adjacent"], meaning: "즉각적인/인접한" },
  { word: "wield", synonyms: ["exercise", "use", "handle"], meaning: "행사하다" },
  { word: "crush", synonyms: ["discourage", "deflate"], meaning: "꺾다" },
  { word: "manner", synonyms: ["way", "fashion", "mode"], meaning: "방법" },
  { word: "uneasy", synonyms: ["apprehensive", "unstable", "disturbed", "ill at ease"], meaning: "불안한" },
];

const day24Words = [
  { word: "sustain", synonyms: ["support", "bear", "uphold", "maintain", "continue"], meaning: "지탱하다/지속하다" },
  { word: "subsequence", synonyms: ["succession", "next in a series"], meaning: "연속" },
  { word: "accumulate", synonyms: ["gather", "collect", "compile", "gradually increase in number"], meaning: "모으다" },
  { word: "assert", synonyms: ["claim", "maintain", "declare", "forcefully establish", "contend"], meaning: "주장하다" },
  { word: "progressive", synonyms: ["advanced", "liberal", "increasing", "continuous"], meaning: "진보적인/점진적인" },
  { word: "strikingly", synonyms: ["remarkably", "noticeably"], meaning: "눈에 띄게" },
  { word: "comparable", synonyms: ["analogous", "similar", "equivalent", "alike"], meaning: "비슷한" },
  { word: "hinder", synonyms: ["interfere with", "hamper", "stunt", "impede"], meaning: "방해하다" },
  { word: "concern", synonyms: ["worry", "interest", "regard", "care"], meaning: "걱정시키다/관심" },
  { word: "presumably", synonyms: ["supposedly", "probably", "thought to be", "it can be assumed"], meaning: "아마" },
  { word: "ritual", synonyms: ["ceremonial"], meaning: "의식적인" },
  { word: "unresolved", synonyms: ["undecided", "undetermined", "unsettled"], meaning: "미정의" },
  { word: "convey", synonyms: ["transmit", "communicate", "deliver", "impart"], meaning: "전달하다" },
  { word: "devise", synonyms: ["invent", "create", "design", "contrive"], meaning: "고안하다" },
  { word: "astonish", synonyms: ["amaze", "surprise", "astound", "shock"], meaning: "깜짝 놀라게 하다" },
  { word: "stringent", synonyms: ["strict", "rigorous", "tight"], meaning: "엄한" },
  { word: "vastly", synonyms: ["greatly", "enormously", "immensely", "exceedingly"], meaning: "대단히" },
  { word: "to a large extent", synonyms: ["for the most part", "mainly", "largely"], meaning: "대체로" },
  { word: "updated", synonyms: ["newer"], meaning: "최신의" },
  { word: "impulse", synonyms: ["stimulus", "basic motivation", "impetus"], meaning: "자극" },
  { word: "evidence", synonyms: ["proof", "verification"], meaning: "증거" },
  { word: "conjuncture", synonyms: ["combination", "connection", "juncture"], meaning: "결합" },
  { word: "aberrant", synonyms: ["abnormal", "deviant", "eccentric", "erratic"], meaning: "정도를 벗어난" },
  { word: "firmly", synonyms: ["securely", "fixedly"], meaning: "단단히" },
  { word: "invariably", synonyms: ["always", "without exception", "constantly"], meaning: "언제나" },
  { word: "sacred", synonyms: ["holy", "divine"], meaning: "신성한" },
  { word: "cramped", synonyms: ["confined", "restricted"], meaning: "비좁은" },
  { word: "outdated", synonyms: ["old-fashioned", "antiquated", "archaic", "outmoded"], meaning: "구식의" },
  { word: "self-confident", synonyms: ["assured", "self-assured"], meaning: "자신감있는" },
  { word: "allay", synonyms: ["reduce", "relieve", "soothe"], meaning: "완화시키다" },
  { word: "authenticity", synonyms: ["genuineness", "realness"], meaning: "진짜" },
  { word: "masked", synonyms: ["concealed", "covered"], meaning: "가면을 쓴" },
  { word: "fracture", synonyms: ["rupture", "crack", "gap", "cleft"], meaning: "균열" },
  { word: "scanty", synonyms: ["scarce", "sparse", "thin", "short", "meager"], meaning: "부족한" },
  { word: "debris", synonyms: ["fragment", "wreckage", "remains", "dreg"], meaning: "파편" },
  { word: "unexpectedly", synonyms: ["surprisingly", "unpredictably"], meaning: "뜻밖에" },
  { word: "marginally", synonyms: ["slightly", "somewhat", "a little"], meaning: "조금" },
  { word: "infrequent", synonyms: ["uncommon", "rare", "unusual"], meaning: "드문" },
  { word: "capacity", synonyms: ["ability", "talent", "flair"], meaning: "능력" },
  { word: "conceive", synonyms: ["imagine", "envision", "visualize"], meaning: "상상하다" },
  { word: "immobile", synonyms: ["unable to move", "motionless"], meaning: "정지한" },
  { word: "milestone", synonyms: ["significant event", "important event"], meaning: "획기적인 사건" },
  { word: "tempting", synonyms: ["attractive", "appealing", "inviting", "appetizing"], meaning: "매력적인" },
  { word: "antagonistic", synonyms: ["hostile", "adversarial"], meaning: "적대하는" },
  { word: "prized", synonyms: ["outstanding", "prominent", "valued"], meaning: "뛰어난" },
  { word: "cognitive", synonyms: ["mental"], meaning: "인지의" },
  { word: "refuge", synonyms: ["shelter", "place of safety", "sanctuary"], meaning: "피난처" },
  { word: "full sweep", synonyms: ["whole range"], meaning: "모든 범위" },
  { word: "notwithstanding", synonyms: ["despite", "in spite of"], meaning: "에도 불구하고" },
  { word: "trap", synonyms: ["catch", "capture"], meaning: "잡다" },
  { word: "methodical", synonyms: ["systematic", "organized"], meaning: "체계적인" },
  { word: "emergency", synonyms: ["crisis", "exigency"], meaning: "위기" },
  { word: "gain", synonyms: ["increase", "rise", "growth", "augmentation"], meaning: "증가" },
  { word: "signal", synonyms: ["cue", "indicate", "communicate", "gesture", "motion"], meaning: "신호를 보내다" },
  { word: "issue", synonyms: ["matter", "point", "question"], meaning: "문제" },
  { word: "obliterate", synonyms: ["delete", "erase", "efface"], meaning: "지우다" },
  { word: "in addition", synonyms: ["moreover"], meaning: "게다가" },
  { word: "at the same time", synonyms: ["simultaneously"], meaning: "동시에" },
  { word: "voracious predator", synonyms: ["strong competitor"], meaning: "탐욕스러운 포식자" },
];

const day25Words = [
  { word: "inevitable", synonyms: ["unavoidable", "certain", "inescapable"], meaning: "불가피한" },
  { word: "consequent", synonyms: ["resultant", "resulting", "eventual", "ensuing"], meaning: "결과로서 일어나는" },
  { word: "decimation", synonyms: ["destruction", "devastation"], meaning: "대량파괴" },
  { word: "evoke", synonyms: ["arouse", "cause", "draw", "produce", "induce"], meaning: "불러일으키다" },
  { word: "vulnerable", synonyms: ["easily damaged", "susceptible", "weak", "open to attack"], meaning: "취약한" },
  { word: "elaborate", synonyms: ["detailed", "more complex", "complicated", "make detailed"], meaning: "정교한/자세히 설명하다" },
  { word: "enigmatic", synonyms: ["mysterious", "puzzling"], meaning: "불가사의한" },
  { word: "coincide with", synonyms: ["correspond to", "accord with"], meaning: "일치하다" },
  { word: "seemingly", synonyms: ["apparently", "ostensibly"], meaning: "외견상으로" },
  { word: "wrought", synonyms: ["created", "formed", "manufactured"], meaning: "만들어진" },
  { word: "obstacle", synonyms: ["barrier", "hindrance", "impediment", "obstruction"], meaning: "장애물" },
  { word: "lucrative", synonyms: ["profitable", "gainful", "advantageous"], meaning: "수익성이 좋은" },
  { word: "extensive", synonyms: ["widespread", "large", "wide", "broad", "far-reaching"], meaning: "넓은" },
  { word: "dampen", synonyms: ["moisten", "wet", "soak", "saturate"], meaning: "적시다" },
  { word: "opaque", synonyms: ["unclear", "obscure", "impenetrable"], meaning: "불분명한/불투명한" },
  { word: "endorse", synonyms: ["support", "subscribe", "back", "advocate", "sign"], meaning: "지지하다/서명하다" },
  { word: "advent", synonyms: ["arrival", "coming", "introduction", "appearance"], meaning: "출현" },
  { word: "severely", synonyms: ["intensely", "seriously", "sharply"], meaning: "격렬하게" },
  { word: "immutable", synonyms: ["unchangeable", "invariable", "unalterable"], meaning: "불변의" },
  { word: "yardstick", synonyms: ["measure", "criterion", "benchmark", "standard"], meaning: "기준, 척도" },
  { word: "preserve", synonyms: ["protect", "save", "retain", "maintain", "conserve"], meaning: "보호하다" },
  { word: "conviction", synonyms: ["strong belief", "strong opinion", "faith"], meaning: "신념" },
  { word: "hallmark", synonyms: ["feature", "distinguishing trait", "sure signal"], meaning: "특징" },
  { word: "timid", synonyms: ["shy", "fearful", "cowardly"], meaning: "소심한" },
  { word: "robust", synonyms: ["strong", "vigorous", "healthy", "stalwart"], meaning: "튼튼한" },
  { word: "discard", synonyms: ["throw away", "abandon", "reject", "dispose of", "cast aside"], meaning: "버리다" },
  { word: "complicated", synonyms: ["complex", "intricate", "elaborate"], meaning: "복잡한" },
  { word: "apart from", synonyms: ["besides", "except for", "excluding"], meaning: "~을 제외하고" },
  { word: "graduate to", synonyms: ["progress to", "advance to", "proceed to"], meaning: "나아가다" },
  { word: "demonstrate", synonyms: ["indicate", "show", "manifest"], meaning: "나타내다" },
  { word: "deluxe", synonyms: ["lavish", "luxurious", "opulent", "rich"], meaning: "호화로운" },
  { word: "dispute", synonyms: ["argue", "contend", "argument", "disagreement", "debate"], meaning: "논쟁하다/논쟁" },
  { word: "convention", synonyms: ["usually practiced", "custom", "tradition", "rule"], meaning: "관습" },
  { word: "rival", synonyms: ["competing", "competitive", "conflicting", "competitor", "antagonist", "opponent", "compete with", "match"], meaning: "경쟁하는/경쟁자/~와 경쟁하다" },
  { word: "modulate", synonyms: ["adjust", "regulate", "tune"], meaning: "조절하다" },
  { word: "universal", synonyms: ["used everywhere", "general"], meaning: "보편적인" },
  { word: "equivalent", synonyms: ["equal", "comparable", "even", "commensurate"], meaning: "상응하는" },
  { word: "sparsely", synonyms: ["thinly", "widely scattered"], meaning: "드문드문" },
  { word: "exceed", synonyms: ["go beyond", "surpass", "have a greater number than"], meaning: "초과하다" },
  { word: "linger", synonyms: ["remain", "stay"], meaning: "남다" },
  { word: "innovative", synonyms: ["original", "inventive", "creative", "ingenious"], meaning: "독창적인" },
  { word: "antiquity", synonyms: ["ancient times", "distant past"], meaning: "고대" },
  { word: "impending", synonyms: ["approaching", "imminent"], meaning: "임박한" },
  { word: "doctrine", synonyms: ["tenet", "principle", "dogma"], meaning: "교리, 원칙" },
  { word: "contribute", synonyms: ["donate", "endow", "pitch in with", "conduce"], meaning: "기부하다" },
  { word: "cease", synonyms: ["stop", "halt", "end", "terminate"], meaning: "멈추다" },
  { word: "prior to", synonyms: ["before", "previous to", "ahead of"], meaning: "~보다 전에" },
  { word: "groom", synonyms: ["clean", "tidy"], meaning: "다듬다" },
  { word: "diversity", synonyms: ["variety", "difference"], meaning: "다양성" },
  { word: "correlate", synonyms: ["match", "connect", "link"], meaning: "연관시키다" },
  { word: "elite", synonyms: ["upper class", "upper crust", "aristocracy", "gentry"], meaning: "최상류층" },
  { word: "stratify", synonyms: ["layer"], meaning: "층을 이루다" },
  { word: "lessen", synonyms: ["reduce", "abate", "diminish"], meaning: "줄이다" },
  { word: "upset", synonyms: ["disturb", "agitate", "unsettle", "worry"], meaning: "불안하게 하다" },
  { word: "accrete", synonyms: ["come together", "accumulate"], meaning: "하나로 합쳐지다" },
  { word: "uninterrupted", synonyms: ["steady", "ceaseless", "incessant"], meaning: "연속적인" },
];

const day26Words = [
  { word: "offset", synonyms: ["counterbalance", "counteract", "cancel out"], meaning: "상쇄하다" },
  { word: "assume", synonyms: ["undertake", "take on", "adopt", "believe", "think", "suppose", "presume"], meaning: "떠맡다/생각하다" },
  { word: "periodically", synonyms: ["regularly", "at intervals", "occasionally"], meaning: "정기적으로/간헐적으로" },
  { word: "cite", synonyms: ["refer to", "mention", "allude to"], meaning: "언급하다" },
  { word: "commonly", synonyms: ["generally", "often", "normally", "usually"], meaning: "보통" },
  { word: "locate", synonyms: ["find", "detect", "discover", "position", "situate", "place"], meaning: "위치 등을 발견하다/두다" },
  { word: "impose", synonyms: ["force", "pressure", "enforce"], meaning: "강요하다" },
  { word: "prerequisite", synonyms: ["requirement", "necessary condition", "precondition"], meaning: "필요조건" },
  { word: "immunity", synonyms: ["exemption", "impunity"], meaning: "면제" },
  { word: "proper", synonyms: ["suitable", "appropriate", "apposite"], meaning: "적절한" },
  { word: "embark on", synonyms: ["start", "begin", "commence"], meaning: "시작하다" },
  { word: "probe", synonyms: ["investigate", "search", "examine", "explore", "exploration", "inquiry"], meaning: "조사하다/탐사" },
  { word: "exhaust", synonyms: ["use up", "deplete", "run out of", "tire", "weary", "fatigue"], meaning: "다 써 버리다/지치게 하다" },
  { word: "exclusive", synonyms: ["only", "sole", "single"], meaning: "유일한" },
  { word: "manipulate", synonyms: ["handle", "control", "operate", "maneuver", "change", "deliberately alter"], meaning: "다루다, 조종하다/조작하다, 속이다" },
  { word: "ongoing", synonyms: ["continued", "constant", "persistent"], meaning: "진행 중인" },
  { word: "primary", synonyms: ["fundamental", "elementary", "basic"], meaning: "기본적인" },
  { word: "interval", synonyms: ["space", "distance", "period"], meaning: "간격" },
  { word: "spark", synonyms: ["bring about", "trigger", "provoke"], meaning: "유발하다" },
  { word: "tenacity", synonyms: ["stubbornness", "determination", "firmness"], meaning: "고집" },
  { word: "distinctive", synonyms: ["characteristic", "peculiar"], meaning: "특유의" },
  { word: "collaborative", synonyms: ["cooperative", "concerted", "joint"], meaning: "협력적인" },
  { word: "deeply ingrained", synonyms: ["firmly established"], meaning: "깊이 베인" },
  { word: "instantaneous", synonyms: ["immediate", "prompt", "on-the-spot"], meaning: "즉각적인" },
  { word: "agitate", synonyms: ["create movement in", "stir", "beat"], meaning: "휘젓다" },
  { word: "in profile", synonyms: ["from side view"], meaning: "옆모습으로" },
  { word: "especially", synonyms: ["particularly", "notably", "specially"], meaning: "특히" },
  { word: "creative", synonyms: ["inventive", "imaginative"], meaning: "창의적인" },
  { word: "rim", synonyms: ["edge", "border", "verge", "margin"], meaning: "가장자리" },
  { word: "anxious", synonyms: ["worried", "concerned", "apprehensive", "uneasy", "eager", "keen", "longing"], meaning: "걱정하는/열망하는" },
  { word: "require", synonyms: ["demand", "call for", "entail", "need"], meaning: "요구하다" },
  { word: "handy", synonyms: ["Convenient"], meaning: "편리한" },
  { word: "rare", synonyms: ["unusual", "infrequent", "scarce", "uncommon"], meaning: "드문" },
  { word: "diligently", synonyms: ["earnestly", "assiduously", "carefully", "industriously"], meaning: "열심히" },
  { word: "mutually exclusive", synonyms: ["different from one another"], meaning: "상호 배타적인" },
  { word: "vacant", synonyms: ["empty", "unoccupied", "void"], meaning: "비어있는" },
  { word: "represent", synonyms: ["depict", "portray", "express"], meaning: "묘사하다" },
  { word: "conclude", synonyms: ["decide", "make a final judgment", "determine"], meaning: "결론 내리다" },
  { word: "impede", synonyms: ["inhibit", "hinder", "obstruct"], meaning: "방해하다" },
  { word: "humble", synonyms: ["modest", "unpretentious", "unassuming"], meaning: "겸손한" },
  { word: "premise", synonyms: ["assumption", "presupposition"], meaning: "가정" },
  { word: "jettison", synonyms: ["release", "discard", "throw away", "cast off"], meaning: "버리다" },
  { word: "segregate", synonyms: ["separate", "seclude", "dissociate", "disunite"], meaning: "분리하다" },
  { word: "innumerable", synonyms: ["countless", "numberless", "numerous"], meaning: "무수한" },
  { word: "havoc", synonyms: ["destruction", "ruin", "devastation", "demolition"], meaning: "대파괴" },
  { word: "dwindle", synonyms: ["decrease", "diminish", "lessen"], meaning: "줄어들다" },
  { word: "concept", synonyms: ["idea", "notion"], meaning: "개념" },
  { word: "sensation", synonyms: ["extraordinary", "exciting"], meaning: "굉장한" },
  { word: "convincing", synonyms: ["persuasive", "compelling", "credible", "cogent"], meaning: "설득력있는" },
  { word: "insight", synonyms: ["understanding", "perception", "sense"], meaning: "통찰력" },
  { word: "naively", synonyms: ["plainly", "candidly", "ingenuously"], meaning: "솔직하게, 순진하게" },
  { word: "vague", synonyms: ["unclear", "uncertain", "imprecise", "obscure"], meaning: "모호한" },
  { word: "associated", synonyms: ["connected", "correlated", "linked"], meaning: "관련된" },
  { word: "amplification", synonyms: ["further explanation"], meaning: "부연설명" },
];

const day27Words = [
  { word: "Remnant", synonyms: ["leftover", "remains", "trace", "relic"], meaning: "나머지" },
  { word: "indispensable", synonyms: ["essential", "necessary", "requisite"], meaning: "필수적인" },
  { word: "undermine", synonyms: ["weaken", "attenuate"], meaning: "악화시키다" },
  { word: "Fashion", synonyms: ["way", "manner", "mode", "shape", "create", "make"], meaning: "방식/만들다, 형성하다" },
  { word: "Prolong", synonyms: ["extend", "lengthen", "protract"], meaning: "연장하다" },
  { word: "adequate", synonyms: ["sufficient", "satisfactory"], meaning: "충분한" },
  { word: "Halt", synonyms: ["stop", "cease"], meaning: "정지시키다" },
  { word: "controversial", synonyms: ["debatable", "disputed", "producing disagreement"], meaning: "논쟁의 여지가 있는" },
  { word: "Match", synonyms: ["equal", "rival", "parallel"], meaning: "필적하다" },
  { word: "enduring", synonyms: ["lasting", "surviving", "everlasting", "perpetual"], meaning: "영속적인" },
  { word: "Restrict", synonyms: ["limit", "confine", "restrain"], meaning: "제한하다" },
  { word: "encompass", synonyms: ["include", "contain", "embrace"], meaning: "포함하다" },
  { word: "consider", synonyms: ["contemplate", "take into account"], meaning: "고려하다" },
  { word: "integrate", synonyms: ["unite", "unify", "synthesize", "interconnect", "consolidate"], meaning: "통합하다" },
  { word: "Startling", synonyms: ["surprising", "astonishing", "alarming"], meaning: "놀라운" },
  { word: "unaccounted for", synonyms: ["not explained"], meaning: "설명되지 않은" },
  { word: "manifest", synonyms: ["indicate", "reveal", "demonstrate", "obvious", "clear", "definite", "evident"], meaning: "나타내다/명백한" },
  { word: "fragile", synonyms: ["easily broken", "delicate", "weak"], meaning: "깨지기 쉬운" },
  { word: "faithful", synonyms: ["accurate", "exact", "precise", "veracious"], meaning: "충실한, 정확한" },
  { word: "concede", synonyms: ["admit", "accept as true", "acknowledge", "grant"], meaning: "인정하다/허락하다" },
  { word: "threaten", synonyms: ["endanger", "menace", "imperil", "jeopardize"], meaning: "위태롭게 하다" },
  { word: "revolutionize", synonyms: ["fundamentally change", "completely change"], meaning: "혁신을 일으키다" },
  { word: "haphazard", synonyms: ["random", "chance", "casual"], meaning: "무계획적인" },
  { word: "mainstay", synonyms: ["important part", "anchor", "buttress"], meaning: "주요 의지물, 대들보" },
  { word: "wholly", synonyms: ["completely", "entirely", "fully", "thoroughly"], meaning: "완전히" },
  { word: "edible", synonyms: ["eatable", "fit to eat", "safe to eat"], meaning: "먹을 수 있는" },
  { word: "legible", synonyms: ["recognizable", "readable"], meaning: "알아볼 수 있는" },
  { word: "scrutinize", synonyms: ["examine", "inspect", "investigate", "probe"], meaning: "조사하다" },
  { word: "in essence", synonyms: ["essentially", "fundamentally", "basically", "in substance"], meaning: "본질적으로" },
  { word: "beneficial", synonyms: ["useful", "helpful", "advantageous", "profitable"], meaning: "유익한" },
  { word: "distribute", synonyms: ["parcel out", "spread", "allot", "apportion"], meaning: "분배하다" },
  { word: "heir", synonyms: ["inheritor", "successor"], meaning: "상속인" },
  { word: "specifically", synonyms: ["specially", "especially", "particularly"], meaning: "특별히" },
  { word: "costly", synonyms: ["expensive", "high-priced"], meaning: "돈이 많이 드는" },
  { word: "yield", synonyms: ["produce", "generate", "give", "cede", "surrender", "hand over"], meaning: "산출하다/양도하다" },
  { word: "channel", synonyms: ["direct"], meaning: "관심, 노력 등을 돌리다, 쏟다" },
  { word: "necessary", synonyms: ["required", "requisite", "essential", "indispensable"], meaning: "필수의" },
  { word: "retrospect", synonyms: ["look back"], meaning: "회고하다" },
  { word: "overview", synonyms: ["summary", "outline", "synopsis"], meaning: "개요" },
  { word: "occasional", synonyms: ["infrequent", "sporadic", "intermittent"], meaning: "가끔의" },
  { word: "respectively", synonyms: ["separately", "individually", "each"], meaning: "각각" },
  { word: "entice", synonyms: ["tempt", "allure", "seduce"], meaning: "유혹하다" },
  { word: "choose", synonyms: ["opt", "select"], meaning: "선택하다" },
  { word: "work out at", synonyms: ["be calculated at"], meaning: "계산되다" },
  { word: "enlist", synonyms: ["enroll", "join", "sign up", "recruit"], meaning: "입대하다, 모집하다" },
  { word: "diminish", synonyms: ["reduce", "decrease", "lessen", "cut", "abate"], meaning: "줄이다" },
  { word: "norm", synonyms: ["rule", "standard"], meaning: "규범" },
  { word: "ostentatious", synonyms: ["showy"], meaning: "과시하는" },
  { word: "desert", synonyms: ["abandon", "forsake", "leave"], meaning: "버리다" },
  { word: "dwelling", synonyms: ["living quarters", "habitation", "residence", "home"], meaning: "거주지" },
  { word: "homogenize", synonyms: ["remove variation within", "make uniform"], meaning: "동질화하다" },
  { word: "up", synonyms: ["increase", "raise", "augment", "multiply"], meaning: "증가시키다" },
  { word: "displace", synonyms: ["supplant", "replace", "move out of position"], meaning: "대체하다/옮기다" },
  { word: "numerous", synonyms: ["very many", "countless", "innumerable"], meaning: "매우 많은" },
  { word: "discharge", synonyms: ["release", "emit", "excrete"], meaning: "방출하다" },
  { word: "defend", synonyms: ["guard"], meaning: "방어하다" },
  { word: "compose", synonyms: ["make up"], meaning: "구성하다" },
];

const day28Words = [
  { word: "abundance", synonyms: ["plenty", "large number", "profusion"], meaning: "다수, 풍부" },
  { word: "onset", synonyms: ["beginning", "start", "commencement"], meaning: "시작" },
  { word: "witness", synonyms: ["observe", "see", "look on"], meaning: "목격하다" },
  { word: "mount", synonyms: ["grow", "increase", "multiply"], meaning: "증가하다" },
  { word: "reinforce", synonyms: ["strengthen", "support", "consolidate", "fortify"], meaning: "강화하다" },
  { word: "intense", synonyms: ["strong", "extreme", "fierce", "acute"], meaning: "강렬한" },
  { word: "involved", synonyms: ["complicated", "intricate", "tangled"], meaning: "복잡한" },
  { word: "solely", synonyms: ["only", "purely", "exclusively", "entirely"], meaning: "오로지" },
  { word: "undergo", synonyms: ["experience", "go through", "suffer"], meaning: "경험하다" },
  { word: "mechanism", synonyms: ["instrument", "device", "apparatus", "means", "method", "way"], meaning: "장치/방법" },
  { word: "speculate", synonyms: ["guess", "suppose", "hypothesize", "assume"], meaning: "추측하다" },
  { word: "conclusively", synonyms: ["decisively", "definitively"], meaning: "결정적으로" },
  { word: "significantly", synonyms: ["considerably", "remarkably", "markedly"], meaning: "상당히" },
  { word: "adopt", synonyms: ["take up", "begin to use", "select"], meaning: "채택하다" },
  { word: "staple", synonyms: ["basic item", "regular feature", "basic feature", "basic", "primary"], meaning: "주요 상품/기본적인" },
  { word: "secrete", synonyms: ["release", "produce", "excrete", "conceal", "hide", "veil"], meaning: "분비하다/숨기다" },
  { word: "Pursue", synonyms: ["practice", "conduct", "perform"], meaning: "실행하다" },
  { word: "conserve", synonyms: ["keep", "protect", "save", "preserve"], meaning: "보존하다" },
  { word: "Toil", synonyms: ["work hard", "labor"], meaning: "힘써 일하다" },
  { word: "approximate", synonyms: ["rough", "close", "near", "resemble"], meaning: "대략적인/비슷하다" },
  { word: "monumental", synonyms: ["huge", "massive", "great and significant"], meaning: "엄청나게 큰" },
  { word: "contract", synonyms: ["shorten", "constrict"], meaning: "줄이다" },
  { word: "puzzling", synonyms: ["difficult to explain", "enigmatic"], meaning: "영문모름" },
  { word: "Divest", synonyms: ["deprive", "strip", "despoil"], meaning: "박탈하다" },
  { word: "pacifier", synonyms: ["peacemaker", "arbitrator", "mediator", "intermediary"], meaning: "중재자" },
  { word: "permanently", synonyms: ["forever", "eternally", "perpetually", "everlastingly"], meaning: "영구히" },
  { word: "estimate", synonyms: ["assess", "evaluate", "judge", "calculate"], meaning: "평가하다, 추산하다" },
  { word: "hurdle", synonyms: ["obstacle", "barrier", "hindrance", "impediment"], meaning: "장애물" },
  { word: "relish", synonyms: ["enjoy", "like", "delight in", "revel in"], meaning: "즐기다" },
  { word: "simulate", synonyms: ["imitate", "pretend", "feign"], meaning: "흉내내다" },
  { word: "hover", synonyms: ["drift", "float", "stay on the top"], meaning: "떠다니다" },
  { word: "display", synonyms: ["show", "exhibit", "present"], meaning: "보여주다" },
  { word: "ominous", synonyms: ["foreboding", "portentous", "threatening"], meaning: "불길한" },
  { word: "stretch", synonyms: ["extend", "lengthen"], meaning: "늘이다" },
  { word: "concur", synonyms: ["agree", "assent", "consent"], meaning: "동의하다" },
  { word: "crisis", synonyms: ["critical situation", "emergency"], meaning: "위기" },
  { word: "amplitude", synonyms: ["size", "extent", "magnitude"], meaning: "크기, 규모" },
  { word: "disintegrate", synonyms: ["break down", "fall apart", "crumble"], meaning: "붕괴되다" },
  { word: "liken to", synonyms: ["compare to"], meaning: "~에 비유하다" },
  { word: "immoral", synonyms: ["improper", "corrupt", "vicious"], meaning: "부도덕한" },
  { word: "instigate", synonyms: ["cause", "provoke", "trigger", "incite"], meaning: "유발하다" },
  { word: "extraordinary", synonyms: ["exceptional", "unusual", "remarkable"], meaning: "비범한" },
  { word: "resurgence", synonyms: ["comeback", "revival", "rebirth"], meaning: "재기" },
  { word: "patent", synonyms: ["evident", "obvious", "apparent", "manifest"], meaning: "명백한" },
  { word: "regular", synonyms: ["routine", "ordinary", "consistent"], meaning: "정기적인" },
  { word: "by virtue of", synonyms: ["because of", "thanks to", "on account of"], meaning: "~때문에" },
  { word: "sever", synonyms: ["cut", "cut off", "part", "separate", "divide"], meaning: "자르다" },
  { word: "in conjunction with", synonyms: ["concomitant with", "together with", "along with"], meaning: "~와 함께" },
  { word: "confidence", synonyms: ["certainty", "assurance", "faith"], meaning: "확신" },
  { word: "distinguish", synonyms: ["differentiate", "tell apart", "discern"], meaning: "구별하다" },
  { word: "on the contrary", synonyms: ["conversely", "on the other hand"], meaning: "그와는 반대로" },
  { word: "Preponderance", synonyms: ["Majority"], meaning: "대부분" },
  { word: "Intermingle", synonyms: ["mix", "blend"], meaning: "섞이다" },
  { word: "Merchandise", synonyms: ["goods", "product", "commodity"], meaning: "상품" },
  { word: "delicate", synonyms: ["fragile", "brittle", "dainty", "exquisite", "fine"], meaning: "깨지기 쉬운/섬세한" },
  { word: "Promising", synonyms: ["likely", "hopeful"], meaning: "유망한" },
  { word: "Gesture", synonyms: ["a movement made with the head, hand or arm"], meaning: "몸짓" },
];

const day29Words = [
  { word: "Analogous", synonyms: ["similar", "comparable", "like", "parallel"], meaning: "유사한" },
  { word: "Repercussion", synonyms: ["effect", "consequence", "result"], meaning: "영향" },
  { word: "Impart", synonyms: ["give", "provide", "bestow", "offer", "grant"], meaning: "주다" },
  { word: "Foster", synonyms: ["encourage", "promote"], meaning: "조장하다" },
  { word: "Elongate", synonyms: ["stretch", "lengthen", "extend", "prolong"], meaning: "늘이다" },
  { word: "in tandem with", synonyms: ["in association with", "in conjunction with"], meaning: "~와 협력하여" },
  { word: "transition", synonyms: ["change", "alternation", "shift"], meaning: "변화" },
  { word: "scarce", synonyms: ["limited", "short in supply", "not readily available", "rare"], meaning: "부족한" },
  { word: "clear", synonyms: ["apparent", "obvious", "lucid", "remove", "clean"], meaning: "분명한/치우다" },
  { word: "relentless", synonyms: ["continuous", "unceasing", "persistent"], meaning: "끊임없는" },
  { word: "intrinsic", synonyms: ["inherent", "innate"], meaning: "고유의" },
  { word: "compact", synonyms: ["dense", "thick", "smaller", "pocket-sized", "little", "compress", "condense"], meaning: "빽빽한/작은/압축하다" },
  { word: "predominantly", synonyms: ["mainly", "primarily", "mostly", "largely"], meaning: "주로" },
  { word: "widespread", synonyms: ["prevalent", "broadly accepted", "common"], meaning: "널리 퍼진" },
  { word: "perishable", synonyms: ["likely to decay", "likely to spoil", "spoilable"], meaning: "잘 상하는" },
  { word: "myriad", synonyms: ["not permanent", "multitude", "millions", "countless", "innumerable", "numerous"], meaning: "영원하지않는/무수히 많음/무수한" },
  { word: "found", synonyms: ["establish", "create", "set up"], meaning: "창설하다" },
  { word: "swiftly", synonyms: ["quickly", "speedily", "rapidly"], meaning: "빠르게" },
  { word: "crucially", synonyms: ["decisively", "critically", "definitively"], meaning: "결정적으로" },
  { word: "scope", synonyms: ["extent", "range", "reach"], meaning: "범위" },
  { word: "projection", synonyms: ["estimate", "calculation", "forecast", "prediction"], meaning: "추정, 예상" },
  { word: "feature", synonyms: ["characteristic", "attribute", "quality"], meaning: "특징" },
  { word: "employ", synonyms: ["use", "utilize", "make use of"], meaning: "사용하다" },
  { word: "proportion", synonyms: ["percentage", "rate", "size", "magnitude"], meaning: "비율/크기" },
  { word: "delusive", synonyms: ["deceptive", "unreliable", "misleading"], meaning: "현혹시키는" },
  { word: "seamless", synonyms: ["perfectly smooth"], meaning: "아주 매끄러운" },
  { word: "embellishment", synonyms: ["decoration", "ornamentation", "adornment"], meaning: "장식" },
  { word: "sterile", synonyms: ["barren", "unproductive", "infertile"], meaning: "척박한" },
  { word: "in response to", synonyms: ["in reaction to"], meaning: "~에 대한 대응으로" },
  { word: "from time to time", synonyms: ["occasionally", "now and then"], meaning: "가끔" },
  { word: "ambiguous", synonyms: ["open to various interpretations", "uncertain", "obscure"], meaning: "모호한" },
  { word: "out of sight", synonyms: ["hidden", "invisible"], meaning: "보이지 않는 곳에" },
  { word: "perplexed", synonyms: ["puzzled", "bewildered"], meaning: "당혹스러운" },
  { word: "despondent", synonyms: ["unhappy", "discouraged", "depressed"], meaning: "낙담한" },
  { word: "collide", synonyms: ["hit each other", "crash", "strike"], meaning: "충돌하다" },
  { word: "assessment", synonyms: ["evaluation", "appraisal"], meaning: "평가" },
  { word: "vital", synonyms: ["essential", "important", "significant"], meaning: "매우 중요한" },
  { word: "shrivel", synonyms: ["dry up", "wither", "wilt"], meaning: "시들다" },
  { word: "dissent", synonyms: ["oppose", "object", "express disagreement"], meaning: "이의를 제기하다" },
  { word: "elegant", synonyms: ["sophisticated", "graceful", "refined"], meaning: "세련된" },
  { word: "qualify", synonyms: ["meet the requirement", "entitle", "empower"], meaning: "자격을 갖추다" },
  { word: "evolve", synonyms: ["develop", "progress"], meaning: "발전하다" },
  { word: "despite", synonyms: ["in spite of", "notwithstanding"], meaning: "~에도 불구하고" },
  { word: "emergence", synonyms: ["appearance", "advent", "rise"], meaning: "출현" },
  { word: "surplus", synonyms: ["excess", "redundancy", "extra goods"], meaning: "과잉" },
  { word: "distant", synonyms: ["faraway", "remote"], meaning: "먼" },
  { word: "aim", synonyms: ["goal", "objective", "purpose", "attempt"], meaning: "목적/목표하다" },
  { word: "in the ascendant", synonyms: ["rising in importance"], meaning: "상승중인" },
  { word: "draw", synonyms: ["attract", "engage"], meaning: "끌다" },
  { word: "overlie", synonyms: ["cover", "overspread"], meaning: "~위 가로놓이다" },
  { word: "signature", synonyms: ["identifying mark"], meaning: "서명" },
  { word: "devoid of", synonyms: ["lacking in", "destitute of"], meaning: "결여된" },
  { word: "vessel", synonyms: ["ship", "boat", "craft"], meaning: "배" },
  { word: "be incorporated in", synonyms: ["be part of"], meaning: "포함되다" },
  { word: "trauma", synonyms: ["Damage"], meaning: "외상" },
];

const day30Words = [
  { word: "pose", synonyms: ["present", "create", "give rise to"], meaning: "일으키다" },
  { word: "principal", synonyms: ["most important", "major", "main", "prime"], meaning: "주요한" },
  { word: "assorted", synonyms: ["various", "varied", "diverse"], meaning: "다채로운" },
  { word: "ruthlessly", synonyms: ["without mercy", "relentlessly", "cruelly"], meaning: "무자비하게" },
  { word: "fluctuate", synonyms: ["change", "vary"], meaning: "변동하다" },
  { word: "viability", synonyms: ["ability to exist", "ability to live", "feasibility"], meaning: "생존능력/실행가능성" },
  { word: "precarious", synonyms: ["unstable", "insecure", "uncertain"], meaning: "불안정한" },
  { word: "imply", synonyms: ["suggest", "indicate", "connote"], meaning: "시사하다" },
  { word: "diverge", synonyms: ["separate", "move apart", "part", "branch"], meaning: "갈라지다" },
  { word: "previously", synonyms: ["formerly", "before", "antecedently"], meaning: "이전에" },
  { word: "Portray", synonyms: ["depict", "show", "picture", "describe"], meaning: "묘사하다" },
  { word: "Suitable", synonyms: ["appropriate", "proper", "apt"], meaning: "적절한" },
  { word: "Retard", synonyms: ["slow down", "delay"], meaning: "지체시키다" },
  { word: "Entirely", synonyms: ["completely", "wholly", "totally", "thoroughly"], meaning: "완전히" },
  { word: "abruptly", synonyms: ["suddenly", "unexpectedly"], meaning: "갑자기" },
  { word: "instructive", synonyms: ["informative", "educational", "helpful", "useful"], meaning: "교육적인" },
  { word: "converse", synonyms: ["opposite", "reverse"], meaning: "반대의" },
  { word: "shortcoming", synonyms: ["weakness", "disadvantage", "defect", "failing"], meaning: "결점" },
  { word: "Vicinity", synonyms: ["neighborhood", "area", "closeness", "proximity"], meaning: "주변/근접" },
  { word: "Abort", synonyms: ["quit", "halt", "call off"], meaning: "중단하다" },
  { word: "broaden", synonyms: ["widen", "expand", "enlarge", "develop"], meaning: "넓히다" },
  { word: "whereas", synonyms: ["While"], meaning: "~에 반하다" },
  { word: "prodigious", synonyms: ["massive", "enormous"], meaning: "막대한" },
  { word: "Artisan", synonyms: ["craftsman", "craftsperson"], meaning: "장인" },
  { word: "Motif", synonyms: ["design", "pattern", "device"], meaning: "무늬" },
  { word: "Antique", synonyms: ["ancient", "archaic", "old"], meaning: "고대의" },
  { word: "incessantly", synonyms: ["constantly", "continuously", "persistently"], meaning: "끊임없이" },
  { word: "Habitat", synonyms: ["environment", "home", "dwelling", "living quarters"], meaning: "거주지" },
  { word: "steadfastly", synonyms: ["firmly", "solidly", "resolutely"], meaning: "확고하게" },
  { word: "Keenly", synonyms: ["deeply", "intensely", "acutely"], meaning: "강렬하게" },
  { word: "intercourse", synonyms: ["exchange", "interchange"], meaning: "교환" },
  { word: "episode", synonyms: ["event", "occurrence", "incident", "happening"], meaning: "하나의 사건" },
  { word: "bound for", synonyms: ["going to", "destined for"], meaning: "~행의" },
  { word: "penchant", synonyms: ["inclination", "tendency", "fondness", "liking"], meaning: "경향" },
  { word: "incipient", synonyms: ["initial", "beginning"], meaning: "초기의" },
  { word: "Distort", synonyms: ["misrepresent", "twist", "falsify"], meaning: "왜곡하다" },
  { word: "redundancy", synonyms: ["duplication", "superfluity", "extra capacity"], meaning: "불필요한 중복" },
  { word: "subject to", synonyms: ["susceptible to", "likely to"], meaning: "~에 영향을 받기 쉬운" },
  { word: "bountiful", synonyms: ["abundant", "plentiful", "ample", "prolific"], meaning: "풍부한" },
  { word: "Deter", synonyms: ["stop", "preclude", "prevent", "inhibit"], meaning: "방해하다" },
  { word: "roundabout", synonyms: ["indirect", "circuitous"], meaning: "간접적인" },
  { word: "Dim", synonyms: ["faint", "weak", "obscure"], meaning: "희미한" },
  { word: "dubious", synonyms: ["suspected", "suspicious", "distrustfully questionable"], meaning: "의심스러운" },
  { word: "Alarm", synonyms: ["fear", "fright", "terror", "surprise", "startle", "dismay"], meaning: "공포/놀라게하다" },
  { word: "eminent", synonyms: ["distinguished", "outstanding", "prominent"], meaning: "뛰어난" },
  { word: "perceptibly", synonyms: ["noticeably", "appreciably", "sensibly"], meaning: "상당히" },
  { word: "ubiquitous", synonyms: ["omnipresent", "universal"], meaning: "어디에서나 존재하는" },
  { word: "dryness", synonyms: ["aridity", "aridness", "drought"], meaning: "건조" },
  { word: "constricted", synonyms: ["narrow", "contracted"], meaning: "좁은" },
  { word: "elicit", synonyms: ["call forth", "obtain", "extract"], meaning: "정보, 반응을 끌어내다" },
  { word: "intervening years", synonyms: ["between years"], meaning: "사이에 있는 세월" },
  { word: "embrace", synonyms: ["accept", "take up", "receive", "adopt"], meaning: "받아들이다" },
  { word: "efficacy", synonyms: ["effectiveness", "efficiency", "potency"], meaning: "효능" },
  { word: "reckless", synonyms: ["careless", "heedless", "inadvertent"], meaning: "부주의한" },
  { word: "diversification", synonyms: ["the emergence of many varieties"], meaning: "다양한" },
  { word: "dismiss", synonyms: ["ignore", "disregard"], meaning: "무시하다" },
  { word: "etch", synonyms: ["cut", "carve", "engrave"], meaning: "새기다" },
  { word: "precision", synonyms: ["Accuracy"], meaning: "정확성" },
  { word: "currently", synonyms: ["at the present time"], meaning: "현재는" },
];
